// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0ab435b455d76c76 "Eventis (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Closed' | 'Opened' // Variant
 * question?: string // Question
 * answer?: string // Answer
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-545RPIJJ.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-5D5Y4IKK.js";
import { routes } from "./chunks/chunk-MNEP7H2N.js";

// virtual:accordion
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Accordion-b01K.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["q8pGaGd5O", "xt7gZITj2"];
var serializationHash = "framer-bcjR9";
var variantClassNames = {
	q8pGaGd5O: "framer-v-2ofik",
	xt7gZITj2: "framer-v-1mdrbxb",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.4,
	ease: [0.12, 0.23, 0.5, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Closed: "q8pGaGd5O",
	Opened: "xt7gZITj2",
};
var getProps = ({ answer, height, id, question, width, ...props }) => {
	return {
		...props,
		BKqc4FBYW:
			question ??
			props.BKqc4FBYW ??
			"How does Nikea differ from other identity management platforms?",
		rFqdOggUD:
			answer ??
			props.rFqdOggUD ??
			"Nikea prioritizes security at its core, offering advanced telemetry and flexible integration options. Unlike other platforms, Nikea focuses on delivering precise control and comprehensive protection for all your identity and access management needs.",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "q8pGaGd5O",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		BKqc4FBYW,
		rFqdOggUD,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "q8pGaGd5O",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapnelcqp = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("xt7gZITj2");
	});
	const onTapeksdm3 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("q8pGaGd5O");
	});
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "xt7gZITj2") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-2ofik",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Closed"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"q8pGaGd5O"}
						onTap={onTapnelcqp}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-d87dc5f7-2638-4b77-9368-a8568c56fcca, rgb(38, 38, 38))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-12cbfa94-9c5f-41d3-a67b-614d50367bfe, rgb(17, 17, 20))",
							borderBottomLeftRadius: 24,
							borderBottomRightRadius: 24,
							borderTopLeftRadius: 24,
							borderTopRightRadius: 24,
							...style,
						}}
						{...addPropertyOverrides(
							{
								xt7gZITj2: {
									"data-framer-name": "Opened",
									onTap: onTapeksdm3,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1bfxw6j"}
							data-framer-name={"Question Wrap"}
							layoutDependency={layoutDependency}
							layoutId={"fQVmjm5M8"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1giujxm"}
								data-framer-name={"Question"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"kbQLHToPj"}
								style={{
									"--extracted-1eung3n":
										"var(--token-c465f8c5-7fa9-436d-b203-2cb129c31fb1, rgb(237, 237, 237))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={BKqc4FBYW}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h4
										className={"framer-styles-preset-luad1x"}
										data-styles-preset={"QrpSGcou5"}
										style={{
											"--framer-text-color":
												"var(--extracted-1eung3n, var(--token-c465f8c5-7fa9-436d-b203-2cb129c31fb1, rgb(237, 237, 237)))",
										}}
									>
										{
											"How does Nikea differ from other identity management platforms?"
										}
									</motion.h4>
								</React.Fragment>
							</RichText>
							<motion.div
								className={"framer-1uq4sbn"}
								data-framer-name={"Plus"}
								layoutDependency={layoutDependency}
								layoutId={"WfICsRGN5"}
								style={{
									backgroundColor:
										"var(--token-9a7303fe-2324-4aa1-bbd4-e1f1d449de82, rgba(255, 255, 255, 0.12))",
									borderBottomLeftRadius: 999,
									borderBottomRightRadius: 999,
									borderTopLeftRadius: 999,
									borderTopRightRadius: 999,
								}}
							>
								<motion.div
									className={"framer-106le8i"}
									layoutDependency={layoutDependency}
									layoutId={"AjB9h5irj"}
									style={{
										backgroundColor:
											"var(--token-c465f8c5-7fa9-436d-b203-2cb129c31fb1, rgb(237, 237, 237))",
										borderBottomLeftRadius: 99,
										borderBottomRightRadius: 99,
										borderTopLeftRadius: 99,
										borderTopRightRadius: 99,
										rotate: 90,
									}}
								/>
								<motion.div
									className={"framer-14dyc7s"}
									layoutDependency={layoutDependency}
									layoutId={"LJmr9Adyc"}
									style={{
										backgroundColor:
											"var(--token-c465f8c5-7fa9-436d-b203-2cb129c31fb1, rgb(237, 237, 237))",
										borderBottomLeftRadius: 99,
										borderBottomRightRadius: 99,
										borderTopLeftRadius: 99,
										borderTopRightRadius: 99,
										rotate: 0,
									}}
									variants={{
										xt7gZITj2: {
											rotate: 90,
										},
									}}
								/>
							</motion.div>
						</motion.div>
						{isDisplayed() && (
							<RichText
								__fromCanvasComponent={true}
								className={"framer-40kmk6"}
								data-framer-name={"Supporting text"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"OjFXmsPd4"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-c465f8c5-7fa9-436d-b203-2cb129c31fb1, rgb(237, 237, 237))",
									"--framer-paragraph-spacing": "0px",
									opacity: 0.51,
								}}
								text={rFqdOggUD}
								variants={{
									xt7gZITj2: {
										"--extracted-r6o4lv":
											"var(--token-80ffe7cf-9d09-4fa3-9c39-3c4b6492f37f, rgb(191, 191, 191))",
										opacity: 1,
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										xt7gZITj2: {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-dsr0r"}
														data-styles-preset={"Erxl6HnxD"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-80ffe7cf-9d09-4fa3-9c39-3c4b6492f37f, rgb(191, 191, 191)))",
														}}
													>
														{
															"Nikea prioritizes security at its core, offering advanced telemetry and flexible integration options. Unlike other platforms, Nikea focuses on delivering precise control and comprehensive protection for all your identity and access management needs."
														}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-dsr0r"}
										data-styles-preset={"Erxl6HnxD"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-c465f8c5-7fa9-436d-b203-2cb129c31fb1, rgb(237, 237, 237)))",
										}}
									>
										{
											"Nikea prioritizes security at its core, offering advanced telemetry and flexible integration options. Unlike other platforms, Nikea focuses on delivering precise control and comprehensive protection for all your identity and access management needs."
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-bcjR9.framer-w5y679, .framer-bcjR9 .framer-w5y679 { display: block; }",
	".framer-bcjR9.framer-2ofik { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 24px; position: relative; width: 916px; will-change: var(--framer-will-change-override, transform); }",
	".framer-bcjR9 .framer-1bfxw6j { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-bcjR9 .framer-1giujxm { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-bcjR9 .framer-1uq4sbn { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 36px); justify-content: center; overflow: visible; padding: 6px; position: relative; width: 36px; }",
	".framer-bcjR9 .framer-106le8i, .framer-bcjR9 .framer-14dyc7s { flex: none; height: 20px; left: calc(50.00000000000002% - 2px / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 20px / 2); width: 2px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-bcjR9 .framer-40kmk6 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 868px; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-bcjR9.framer-v-1mdrbxb .framer-40kmk6 { width: 100%; }",
	...css2,
	...css,
	'.framer-bcjR9[data-border="true"]::after, .framer-bcjR9 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerZQOhajJw3 = withCSS(Component, css3, "framer-bcjR9");
var stdin_default = FramerZQOhajJw3;
FramerZQOhajJw3.displayName = "Accordion";
FramerZQOhajJw3.defaultProps = {
	height: 84,
	width: 916,
};
addPropertyControls(FramerZQOhajJw3, {
	variant: {
		options: ["q8pGaGd5O", "xt7gZITj2"],
		optionTitles: ["Closed", "Opened"],
		title: "Variant",
		type: ControlType.Enum,
	},
	BKqc4FBYW: {
		defaultValue:
			"How does Nikea differ from other identity management platforms?",
		displayTextArea: false,
		title: "Question",
		type: ControlType.String,
	},
	rFqdOggUD: {
		defaultValue:
			"Nikea prioritizes security at its core, offering advanced telemetry and flexible integration options. Unlike other platforms, Nikea focuses on delivering precise control and comprehensive protection for all your identity and access management needs.",
		displayTextArea: false,
		title: "Answer",
		type: ControlType.String,
	},
});
addFonts(
	FramerZQOhajJw3,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:accordion
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "q8pGaGd5O",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0ab435b455d76c767a5dea9600bc5786a15f10b45126633827329afa7ac48a86"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AccordionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0ab435b455d76c767a5dea9600bc5786a15f10b45126633827329afa7ac48a86"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var accordion_default = ComponentWithRoot;
export { accordion_default as default };
