// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0ab435b455d76c76 "Eventis (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Primary Button' | 'Primary Phone Button' | 'Glassy Button' | 'Glassy Phone' // Variant
 * label?: string // Label
 * link?: string // Link
 * icon?: boolean // Icon
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-DD6C4KVC.js";
import { Icon } from "./chunks/chunk-BTSBQWPZ.js";
import { routes } from "./chunks/chunk-MNEP7H2N.js";

// virtual:button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Button-ZPU0.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var PhosphorFonts = getFonts(Icon);
var enabledGestures = {
	chB_amfp7: {
		hover: true,
	},
	zYT3w1lx3: {
		hover: true,
	},
};
var cycleOrder = ["chB_amfp7", "E4GQrfmDw", "zYT3w1lx3", "LT1PoTlTW"];
var serializationHash = "framer-wwSlk";
var variantClassNames = {
	chB_amfp7: "framer-v-17lt2kb",
	E4GQrfmDw: "framer-v-1qygui0",
	LT1PoTlTW: "framer-v-jz0nqx",
	zYT3w1lx3: "framer-v-8vcdfs",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.4,
	ease: [0.12, 0.23, 0.5, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Glassy Button": "zYT3w1lx3",
	"Glassy Phone": "LT1PoTlTW",
	"Primary Button": "chB_amfp7",
	"Primary Phone Button": "E4GQrfmDw",
};
var getProps = ({ height, icon, id, label, link, width, ...props }) => {
	return {
		...props,
		enDzQkQtN: icon ?? props.enDzQkQtN ?? true,
		si0GkhZ8V: label ?? props.si0GkhZ8V ?? "Get Ticket",
		U9RyfAHsf: link ?? props.U9RyfAHsf,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "chB_amfp7",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		si0GkhZ8V,
		U9RyfAHsf,
		enDzQkQtN,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "chB_amfp7",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={U9RyfAHsf}
						motionChild={true}
						nodeId={"chB_amfp7"}
						scopeId={"oOadvAdsi"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-17lt2kb", className2, classNames)} framer-1n1lhxq`}
							data-border={true}
							data-framer-name={"Primary Button"}
							layoutDependency={layoutDependency}
							layoutId={"chB_amfp7"}
							ref={refBinding}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-f1c81b52-2a59-4da2-a47f-3f4bfb2f2b58, rgb(1, 30, 255))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backdropFilter: "none",
								backgroundColor:
									"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))",
								borderBottomLeftRadius: 999,
								borderBottomRightRadius: 999,
								borderTopLeftRadius: 999,
								borderTopRightRadius: 999,
								WebkitBackdropFilter: "none",
								...style,
							}}
							variants={{
								"chB_amfp7-hover": {
									"--border-color":
										"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))",
									backdropFilter: "none",
									backgroundColor:
										"var(--token-f1c81b52-2a59-4da2-a47f-3f4bfb2f2b58, rgb(1, 30, 255))",
									WebkitBackdropFilter: "none",
								},
								"zYT3w1lx3-hover": {
									backgroundColor:
										"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))",
								},
								LT1PoTlTW: {
									"--border-color":
										"var(--token-9a7303fe-2324-4aa1-bbd4-e1f1d449de82, rgba(255, 255, 255, 0.12))",
									backdropFilter: "blur(8px)",
									backgroundColor:
										"var(--token-9a7303fe-2324-4aa1-bbd4-e1f1d449de82, rgba(255, 255, 255, 0.12))",
									WebkitBackdropFilter: "blur(8px)",
								},
								zYT3w1lx3: {
									"--border-color":
										"var(--token-9a7303fe-2324-4aa1-bbd4-e1f1d449de82, rgba(255, 255, 255, 0.12))",
									backdropFilter: "blur(8px)",
									backgroundColor:
										"var(--token-9a7303fe-2324-4aa1-bbd4-e1f1d449de82, rgba(255, 255, 255, 0.12))",
									WebkitBackdropFilter: "blur(8px)",
								},
							}}
							{...addPropertyOverrides(
								{
									"chB_amfp7-hover": {
										"data-framer-name": void 0,
									},
									"zYT3w1lx3-hover": {
										"data-framer-name": void 0,
									},
									E4GQrfmDw: {
										"data-framer-name": "Primary Phone Button",
									},
									LT1PoTlTW: {
										"data-framer-name": "Glassy Phone",
									},
									zYT3w1lx3: {
										"data-framer-name": "Glassy Button",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-61mkzd"}
								data-framer-name={"Get Ticket"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"emJs69E3S"}
								style={{
									"--framer-paragraph-spacing": "0px",
								}}
								text={si0GkhZ8V}
								variants={{
									"chB_amfp7-hover": {
										"--extracted-r6o4lv":
											"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))",
									},
									"zYT3w1lx3-hover": {
										"--extracted-r6o4lv":
											"var(--token-440020f8-b9e1-49ea-9687-1ea12b43b3de, rgb(0, 0, 0))",
									},
									LT1PoTlTW: {
										"--extracted-r6o4lv":
											"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))",
									},
									zYT3w1lx3: {
										"--extracted-r6o4lv":
											"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										"chB_amfp7-hover": {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1xv2ouf"}
														data-styles-preset={"WA7YBUoWN"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255)))",
														}}
													>
														{"Get Ticket"}
													</motion.p>
												</React.Fragment>
											),
										},
										"zYT3w1lx3-hover": {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1xv2ouf"}
														data-styles-preset={"WA7YBUoWN"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-440020f8-b9e1-49ea-9687-1ea12b43b3de, rgb(0, 0, 0)))",
														}}
													>
														{"Get Ticket"}
													</motion.p>
												</React.Fragment>
											),
										},
										LT1PoTlTW: {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1xv2ouf"}
														data-styles-preset={"WA7YBUoWN"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255)))",
														}}
													>
														{"Get Ticket"}
													</motion.p>
												</React.Fragment>
											),
										},
										zYT3w1lx3: {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1xv2ouf"}
														data-styles-preset={"WA7YBUoWN"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255)))",
														}}
													>
														{"Get Ticket"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1xv2ouf"}
										data-styles-preset={"WA7YBUoWN"}
									>
										{"Get Ticket"}
									</motion.p>
								</React.Fragment>
							</RichText>
							{enDzQkQtN && (
								<motion.div
									className={"framer-vy7pcw"}
									data-framer-name={"Right Arrow"}
									layoutDependency={layoutDependency}
									layoutId={"to6zhrXxN"}
									style={{
										backgroundColor:
											"var(--token-f1c81b52-2a59-4da2-a47f-3f4bfb2f2b58, rgb(1, 30, 255))",
										borderBottomLeftRadius: "50%",
										borderBottomRightRadius: "50%",
										borderTopLeftRadius: "50%",
										borderTopRightRadius: "50%",
									}}
									variants={{
										"chB_amfp7-hover": {
											backgroundColor:
												"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))",
										},
										"zYT3w1lx3-hover": {
											backgroundColor:
												"var(--token-440020f8-b9e1-49ea-9687-1ea12b43b3de, rgb(0, 0, 0))",
										},
										LT1PoTlTW: {
											backgroundColor:
												"var(--token-14605fce-5bc9-43c8-a91c-723bc4169ca1, rgba(0, 0, 0, 0))",
										},
										zYT3w1lx3: {
											backgroundColor:
												"var(--token-14605fce-5bc9-43c8-a91c-723bc4169ca1, rgba(0, 0, 0, 0))",
										},
									}}
								>
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-1mbpg5l-container"}
											isAuthoredByUser={true}
											isModuleExternal={true}
											layoutDependency={layoutDependency}
											layoutId={"VmuPgMRmL-container"}
											nodeId={"VmuPgMRmL"}
											rendersWithMotion={true}
											scopeId={"oOadvAdsi"}
											style={{
												rotate: -45,
											}}
											variants={{
												"chB_amfp7-hover": {
													rotate: 0,
												},
												"zYT3w1lx3-hover": {
													rotate: 0,
												},
												LT1PoTlTW: {
													rotate: 0,
												},
											}}
										>
											<Icon
												color={
													"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))"
												}
												height={"100%"}
												iconSearch={"House"}
												iconSelection={"ArrowRight"}
												id={"VmuPgMRmL"}
												layoutId={"VmuPgMRmL"}
												mirrored={false}
												selectByList={true}
												style={{
													height: "100%",
													width: "100%",
												}}
												weight={"bold"}
												width={"100%"}
												{...addPropertyOverrides(
													{
														"chB_amfp7-hover": {
															color:
																"var(--token-f1c81b52-2a59-4da2-a47f-3f4bfb2f2b58, rgb(1, 30, 255))",
														},
													},
													baseVariant,
													gestureVariant,
												)}
											/>
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							)}
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-wwSlk.framer-1n1lhxq, .framer-wwSlk .framer-1n1lhxq { display: block; }",
	".framer-wwSlk.framer-17lt2kb { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 6px 6px 6px 16px; position: relative; text-decoration: none; width: min-content; }",
	".framer-wwSlk .framer-61mkzd { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-wwSlk .framer-vy7pcw { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 38px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 38px; will-change: var(--framer-will-change-override, transform); }",
	".framer-wwSlk .framer-1mbpg5l-container { flex: none; height: 19px; position: relative; width: 19px; }",
	".framer-wwSlk.framer-v-1qygui0.framer-17lt2kb { cursor: unset; }",
	".framer-wwSlk.framer-v-8vcdfs.framer-17lt2kb { width: 169px; }",
	".framer-wwSlk.framer-v-8vcdfs .framer-61mkzd, .framer-wwSlk.framer-v-jz0nqx .framer-61mkzd { flex: 1 0 0px; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-wwSlk.framer-v-jz0nqx.framer-17lt2kb { cursor: unset; width: 169px; }",
	...css,
	'.framer-wwSlk[data-border="true"]::after, .framer-wwSlk [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FrameroOadvAdsi = withCSS(Component, css2, "framer-wwSlk");
var stdin_default = FrameroOadvAdsi;
FrameroOadvAdsi.displayName = "Button";
FrameroOadvAdsi.defaultProps = {
	height: 50,
	width: 149,
};
addPropertyControls(FrameroOadvAdsi, {
	variant: {
		options: ["chB_amfp7", "E4GQrfmDw", "zYT3w1lx3", "LT1PoTlTW"],
		optionTitles: [
			"Primary Button",
			"Primary Phone Button",
			"Glassy Button",
			"Glassy Phone",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	si0GkhZ8V: {
		defaultValue: "Get Ticket",
		displayTextArea: false,
		title: "Label",
		type: ControlType.String,
	},
	U9RyfAHsf: {
		title: "Link",
		type: ControlType.Link,
	},
	enDzQkQtN: {
		defaultValue: true,
		title: "Icon",
		type: ControlType.Boolean,
	},
});
addFonts(
	FrameroOadvAdsi,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PhosphorFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "E4GQrfmDw",
	md: "zYT3w1lx3",
	xl: "chB_amfp7",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0ab435b455d76c767a5dea9600bc5786a15f10b45126633827329afa7ac48a86"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0ab435b455d76c767a5dea9600bc5786a15f10b45126633827329afa7ac48a86"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var button_default = ComponentWithRoot;
export { button_default as default };
