// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0ab435b455d76c76 "Eventis (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Phone' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-MNEP7H2N.js";

// virtual:circle-arrow
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Circle-Arrow-Snt9.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx,
	getFonts,
	SmartComponentScopedContainer,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS as withCSS2,
} from "unframer";
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer";
import * as React2 from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/4S4SnR1GdEzX95H1h5mT/hXnD9L8hCVy3gHrauXbL/Arc.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import * as React from "react";
import { Children, useState } from "react";
import {
	addPropertyControls,
	ControlType,
	RenderTarget,
	withCSS,
} from "unframer";
import { motion } from "unframer";
import hash from "@emotion/hash";
var Arc = withCSS(
	function Arc2(
		props = {
			height: 50,
			width: 50,
		},
	) {
		const hasChildren = Children.count(props.slots) > 0;
		const isCanvas = RenderTarget.current() === RenderTarget.canvas;
		const showCustomPath = hasChildren && props.type === "graphic";
		const isCircle = props.type === "circle";
		const isEllipse = props.type === "ellipse";
		const cylinder = isEllipse ? props.cylinderHeight / 2 : 0;
		let path = createPath(props.flip, cylinder);
		let childPath;
		let viewBox;
		const [renderToString, setRenderToString] = useState();
		React.useEffect(() => {
			if (!isCanvas) return;
			import("react-dom/server").then(({ renderToString: renderToString2 }) => {
				setRenderToString(() => renderToString2);
			});
		}, []);
		if (showCustomPath) {
			const firstChild = getFirstChild(props.slots);
			const svgChild = getFirstChild(firstChild?.props.svg);
			const svgChildCanvas = getFirstChild(firstChild?.props.children);
			if (isCanvas && !svgChildCanvas?.props.frame) {
				return (
					<div style={placeholderStyles}>
						<div style={emojiStyles}>{"\u{1F48E}"}</div>
						<p style={titleStyles}>{"Please connect to Graphic"}</p>
						<p style={subtitleStyles}>
							{"You can only connect the Arc to a Graphic with a single path."}
						</p>
					</div>
				);
			}
			if (isCanvas && svgChildCanvas) {
				if (!renderToString) return null;
				const svgString = renderToString(svgChildCanvas);
				const canvasFrame = svgChildCanvas.props.frame;
				viewBox = `0 0 ${canvasFrame.width} ${canvasFrame.height}`;
				let attributes = svgString.match(/[\w-]+="[^"]*"/g);
				for (const element of attributes) {
					if (element.includes("d=")) {
						childPath = splitAndReplace(element);
					}
				}
			}
			if (!isCanvas && svgChild) {
				let attributes = svgChild.match(/[\w-]+="[^"]*"/g);
				viewBox = svgChild.split("viewBox=")[1];
				viewBox = viewBox.split(">")[0];
				viewBox = viewBox.replace(/^"(.+(?="$))"$/, "$1");
				for (const element of attributes) {
					if (element.includes("d=")) {
						childPath = splitAndReplace(element);
					}
				}
			}
		}
		const id = `curve-${hash(childPath || path)}`;
		let alignmentValue;
		if (props.alignmentBaseline === "top") alignmentValue = "Text Top";
		if (props.alignmentBaseline === "center") alignmentValue = "Central";
		if (props.alignmentBaseline === "bottom") alignmentValue = "Hanging";
		return (
			<motion.div
				style={{
					width: "100%",
					height: "100%",
					// userSelect: "none",
					// pointerEvents: "none",
					position: "relative",
				}}
				draggable={"false"}
			>
				<motion.svg
					className={"transform-origin-center-center"}
					style={{
						width: "100%",
						height: "100%",
						position: "absolute",
						inset: 0,
						transformOrigin: "center",
						willChange: props.rotate && "transform",
					}}
					viewBox={showCustomPath ? viewBox : `0 0 100 100`}
					overflow={"visible"}
					animate={
						isCircle &&
						props.rotate && {
							rotate: 360,
						}
					}
					transition={
						isCircle &&
						props.rotate && {
							duration: 100 / props.rotateSpeed,
							repeat: Infinity,
							ease: "linear",
						}
					}
				>
					<path
						id={id}
						d={showCustomPath ? childPath : path}
						strokeWidth={"none"}
						fill={"transparent"}
					/>
					<text>
						<textPath
							href={`#${id}`}
							startOffset={props.startOffset}
							dominantBaseline={alignmentValue}
							style={{
								...props.font,
								wordSpacing: props.wordSpacing,
								fill: props.color,
							}}
						>
							{props.text}
							{!isCanvas && props.animate && (
								<animate
									attributeName={"startOffset"}
									from={`${props.animateStart}%`}
									to={`${props.animateEnd}%`}
									begin={"0s"}
									dur={`${props.animateDuration}s`}
									repeatCount={"indefinite"}
								/>
							)}
						</textPath>
					</text>
				</motion.svg>
			</motion.div>
		);
	},
	// Work around a bug with framer-motion that calculates a px origin when animating SVG elements.
	[
		".transform-origin-center-center { transform-origin: center center !important; }",
	],
	"blitz-arc-text",
);
var stdin_default = Arc;
Arc.defaultProps = {
	height: 50,
	width: 50,
};
addPropertyControls(Arc, {
	text: {
		title: "Content",
		type: ControlType.String,
		defaultValue: "\u2726 THANK YOU \u2726 FOR VISITING",
		displayTextArea: true,
	},
	type: {
		title: "Type",
		type: ControlType.Enum,
		options: ["circle", "ellipse", "graphic"],
		optionTitles: ["Circle", "Ellipse", "Graphic"],
		defaultValue: true,
	},
	cylinderHeight: {
		title: "Height",
		type: ControlType.Number,
		unit: "px",
		min: 0,
		max: 1e3,
		hidden: ({ type }) => type !== "ellipse",
	},
	rotate: {
		type: ControlType.Boolean,
		title: "Rotate",
		defaultValue: false,
		hidden: ({ type }) => type !== "circle",
	},
	rotateSpeed: {
		type: ControlType.Number,
		title: "Speed",
		min: 0,
		max: 50,
		defaultValue: 5,
		displayStepper: true,
		step: 1,
		hidden: ({ type, rotate }) => type !== "circle" || !rotate,
	},
	slots: {
		type: ControlType.ComponentInstance,
		title: "Graphic",
		hidden: ({ type }) => type !== "graphic",
	},
	alignmentBaseline: {
		title: "Align",
		type: ControlType.Enum,
		options: ["top", "center", "bottom"],
		optionIcons: ["align-top", "align-middle", "align-bottom"],
		defaultValue: "bottom",
		displaySegmentedControl: true,
	},
	flip: {
		type: ControlType.Boolean,
		defaultValue: false,
		title: "Direction",
		enabledTitle: "CW",
		disabledTitle: "CCW",
		hidden: ({ type }) => type === "graphic",
	},
	startOffset: {
		title: "Offset",
		type: ControlType.Number,
		defaultValue: 0,
		max: 360,
		unit: "\xB0",
		step: 0.5,
	},
	color: {
		title: "Color",
		type: ControlType.Color,
		defaultValue: "#999",
	},
	font: {
		type: ControlType.Font,
		title: "Font",
		controls: "extended",
		displayTextAlignment: false,
	},
	wordSpacing: {
		type: ControlType.Number,
		step: 1,
		defaultValue: 0,
		title: "Word",
		displayStepper: true,
	},
	animate: {
		type: ControlType.Boolean,
		defaultValue: false,
		title: "Animate",
	},
	animateStart: {
		type: ControlType.Number,
		min: -200,
		max: 200,
		step: 0.1,
		defaultValue: -50,
		title: "From",
		unit: "%",
		hidden: (props) => !props.animate,
	},
	animateEnd: {
		type: ControlType.Number,
		min: -200,
		max: 200,
		step: 0.1,
		defaultValue: 150,
		title: "To",
		unit: "%",
		hidden: (props) => !props.animate,
	},
	animateDuration: {
		type: ControlType.Number,
		min: 0,
		max: 50,
		defaultValue: 5,
		title: "Time",
		unit: "s",
		displayStepper: true,
		hidden: (props) => !props.animate,
	},
});
function getFirstChild(slots) {
	let firstChild;
	Children.map(slots, (child) => {
		if (firstChild === void 0) {
			firstChild = child;
		}
	});
	return firstChild;
}
var splitAndReplace = (string) => {
	return string.split("=")[1].replace(/['"]+/g, "");
};
var createPath = (flip, cylinder) => {
	const cylinderTop = 50 - cylinder;
	const cylinderBottom = 50 + cylinder;
	return !flip
		? `M 0 50 L 0 ${cylinderTop} A 1 1 0 0 1 100 ${cylinderTop} L 100 50 L 100 ${cylinderBottom} A 1 1 0 0 1 0 ${cylinderBottom} L 0 ${cylinderTop}`
		: `M 0 50 L 0 ${cylinderBottom} A 1 1 0 1 0 100 ${cylinderBottom} L 100 ${cylinderTop} A 1 1 0 1 0 0 ${cylinderTop} L 0 50`;
};
var placeholderStyles = {
	display: "flex",
	width: "100%",
	height: "100%",
	placeContent: "center",
	placeItems: "center",
	flexDirection: "column",
	color: "#96F",
	background: "rgba(136, 85, 255, 0.1)",
	fontSize: 11,
	overflow: "hidden",
};
var emojiStyles = {
	fontSize: 32,
	marginBottom: 10,
};
var titleStyles = {
	margin: 0,
	marginBottom: 10,
	fontWeight: 600,
	textAlign: "center",
};
var subtitleStyles = {
	margin: 0,
	opacity: 0.7,
	maxWidth: 160,
	lineHeight: 1.5,
	textAlign: "center",
};

// /:https://framer.com/m/Circle-Arrow-Snt9.js
var ArcFonts = getFonts(stdin_default);
var enabledGestures = {
	F5QEeGIwI: {
		hover: true,
	},
};
var cycleOrder = ["F5QEeGIwI", "kL4U5ujf4"];
var serializationHash = "framer-ydirc";
var variantClassNames = {
	F5QEeGIwI: "framer-v-1evkps2",
	kL4U5ujf4: "framer-v-zd72qc",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.6,
	ease: [0.12, 0.23, 0.5, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React2.Fragment);
var humanReadableVariantMap = {
	Desktop: "F5QEeGIwI",
	Phone: "kL4U5ujf4",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "F5QEeGIwI",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "F5QEeGIwI",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1evkps2",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"F5QEeGIwI"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								"F5QEeGIwI-hover": {
									"data-framer-name": void 0,
								},
								kL4U5ujf4: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-2xo3xl-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"C6km6NLRn-container"}
								nodeId={"C6km6NLRn"}
								rendersWithMotion={true}
								scopeId={"OTy7B76BS"}
							>
								{_jsx2(stdin_default, {
									alignmentBaseline: "bottom",
									animate: false,
									animateDuration: 5,
									animateEnd: 150,
									animateStart: -50,
									color:
										"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))",
									cylinderHeight: 0,
									flip: true,
									font: {
										fontFamily: '"Inter", sans-serif',
										fontSize: "16px",
										fontStyle: "normal",
										fontWeight: 900,
										letterSpacing: "0em",
										lineHeight: "1em",
									},
									height: "100%",
									id: "C6km6NLRn",
									layoutId: "C6km6NLRn",
									rotate: true,
									rotateSpeed: 5,
									slots: [],
									startOffset: 0,
									style: {
										height: "100%",
										width: "100%",
									},
									text: ".  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . ",
									type: "circle",
									width: "100%",
									wordSpacing: 0,
									...addPropertyOverrides(
										{
											"F5QEeGIwI-hover": {
												rotateSpeed: 1,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<motion2.div
							className={"framer-1591lbq"}
							data-framer-name={"Arrow-up-right"}
							layoutDependency={layoutDependency}
							layoutId={"wU5b04PaF"}
							style={{
								rotate: 135,
							}}
						>
							<SVG
								className={"framer-1jegrtl"}
								data-framer-name={"Arrow-up-right"}
								layout={"position"}
								layoutDependency={layoutDependency}
								layoutId={"PB5okAU23"}
								opacity={1}
								svg={
									'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20"><path d="M 14.167 5.833 L 5.833 14.167 M 6.667 5.833 L 14.167 5.833 L 14.167 13.333" fill="transparent" stroke-width="2" stroke="var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray=""></path></svg>'
								}
								svgContentId={10462818578}
								withExternalLayout={true}
							/>
						</motion2.div>
					</motion2.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-ydirc.framer-rh26x9, .framer-ydirc .framer-rh26x9 { display: block; }",
	".framer-ydirc.framer-1evkps2 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 65px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 65px; }",
	".framer-ydirc .framer-2xo3xl-container { flex: none; height: 43px; position: relative; width: 45px; }",
	".framer-ydirc .framer-1591lbq { flex: none; height: 22px; left: calc(49.29577464788735% - 22px / 2); overflow: visible; position: absolute; top: calc(49.29577464788735% - 22px / 2); width: 22px; z-index: 1; }",
	".framer-ydirc .framer-1jegrtl { flex: none; height: 20px; left: calc(50.00000000000002% - 20px / 2); position: absolute; top: calc(50.00000000000002% - 20px / 2); width: 20px; }",
	".framer-ydirc.framer-v-zd72qc.framer-1evkps2 { cursor: unset; }",
	".framer-ydirc.framer-v-1evkps2.hover .framer-2xo3xl-container { height: 49px; width: 49px; }",
];
var FramerOTy7B76BS = withCSS2(Component, css, "framer-ydirc");
var stdin_default2 = FramerOTy7B76BS;
FramerOTy7B76BS.displayName = "Circle Arrow";
FramerOTy7B76BS.defaultProps = {
	height: 65,
	width: 65,
};
addPropertyControls2(FramerOTy7B76BS, {
	variant: {
		options: ["F5QEeGIwI", "kL4U5ujf4"],
		optionTitles: ["Desktop", "Phone"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts(
	FramerOTy7B76BS,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/mkY5Sgyq51ik0AMrSBwhm9DJg.woff2",
					weight: "900",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/X5hj6qzcHUYv7h1390c8Rhm6550.woff2",
					weight: "900",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/gQhNpS3tN86g8RcVKYUUaKt2oMQ.woff2",
					weight: "900",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/cugnVhSraaRyANCaUtI5FV17wk.woff2",
					weight: "900",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/5HcVoGak8k5agFJSaKa4floXVu0.woff2",
					weight: "900",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/rZ5DdENNqIdFTIyQQiP5isO7M.woff2",
					weight: "900",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/P2Bw01CtL0b9wqygO0sSVogWbo.woff2",
					weight: "900",
				},
			],
		},
		...ArcFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:circle-arrow
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "kL4U5ujf4",
	xl: "F5QEeGIwI",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0ab435b455d76c767a5dea9600bc5786a15f10b45126633827329afa7ac48a86"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CircleArrowFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0ab435b455d76c767a5dea9600bc5786a15f10b45126633827329afa7ac48a86"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var circle_arrow_default = ComponentWithRoot;
export { circle_arrow_default as default };
