// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0ab435b455d76c76 "Eventis (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Closed' | 'Open' // Variant
 * click?: Function // Click
}} Props

 */
import { routes } from "./chunks/chunk-MNEP7H2N.js";

// virtual:cross-icon
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Cross-Icon-Oi81.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["X165QcoAj", "FRgnkpAWf"];
var serializationHash = "framer-uPH7v";
var variantClassNames = {
	FRgnkpAWf: "framer-v-1dnuw6x",
	X165QcoAj: "framer-v-1f52rmj",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Closed: "X165QcoAj",
	Open: "FRgnkpAWf",
};
var getProps = ({ click, height, id, width, ...props }) => {
	return {
		...props,
		kfdTaiDBR: click ?? props.kfdTaiDBR,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "X165QcoAj",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, kfdTaiDBR, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "X165QcoAj",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTaphtvfb2 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (kfdTaiDBR) {
			const res = await kfdTaiDBR(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1f52rmj",
							className,
							classNames,
						)}
						data-framer-name={"Closed"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"X165QcoAj"}
						onTap={onTaphtvfb2}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								FRgnkpAWf: {
									"data-framer-name": "Open",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-d4n7ab"}
							data-framer-name={"Menu"}
							layoutDependency={layoutDependency}
							layoutId={"GMaFMZaQF"}
							style={{
								borderBottomLeftRadius: 60,
								borderBottomRightRadius: 60,
								borderTopLeftRadius: 60,
								borderTopRightRadius: 60,
							}}
						>
							<motion.div
								className={"framer-1383mk6"}
								layoutDependency={layoutDependency}
								layoutId={"JiJbi8udO"}
								style={{
									backgroundColor:
										"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))",
									borderBottomLeftRadius: 3,
									borderBottomRightRadius: 3,
									borderTopLeftRadius: 3,
									borderTopRightRadius: 3,
									opacity: 1,
								}}
								transformTemplate={transformTemplate1}
								variants={{
									FRgnkpAWf: {
										opacity: 0,
									},
								}}
							/>
							<motion.div
								className={"framer-fvs33a"}
								layoutDependency={layoutDependency}
								layoutId={"TxpA7iGFa"}
								style={{
									backgroundColor:
										"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))",
									borderBottomLeftRadius: 3,
									borderBottomRightRadius: 3,
									borderTopLeftRadius: 3,
									borderTopRightRadius: 3,
									rotate: 0,
								}}
								transformTemplate={transformTemplate1}
								variants={{
									FRgnkpAWf: {
										rotate: 45,
									},
								}}
								{...addPropertyOverrides(
									{
										FRgnkpAWf: {
											transformTemplate: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
							<motion.div
								className={"framer-1fp2l5q"}
								layoutDependency={layoutDependency}
								layoutId={"YzWSebmew"}
								style={{
									backgroundColor:
										"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))",
									borderBottomLeftRadius: 3,
									borderBottomRightRadius: 3,
									borderTopLeftRadius: 3,
									borderTopRightRadius: 3,
									opacity: 1,
								}}
								transformTemplate={transformTemplate1}
								variants={{
									FRgnkpAWf: {
										opacity: 0,
									},
								}}
							/>
							<motion.div
								className={"framer-184nf98"}
								layoutDependency={layoutDependency}
								layoutId={"kmaODLDOo"}
								style={{
									backgroundColor:
										"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))",
									borderBottomLeftRadius: 3,
									borderBottomRightRadius: 3,
									borderTopLeftRadius: 3,
									borderTopRightRadius: 3,
									rotate: 0,
								}}
								transformTemplate={transformTemplate1}
								variants={{
									FRgnkpAWf: {
										rotate: -45,
									},
								}}
								{...addPropertyOverrides(
									{
										FRgnkpAWf: {
											transformTemplate: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-uPH7v.framer-a03djy, .framer-uPH7v .framer-a03djy { display: block; }",
	".framer-uPH7v.framer-1f52rmj { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-uPH7v .framer-d4n7ab { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 36px); overflow: hidden; position: relative; width: 36px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-uPH7v .framer-1383mk6 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 200px); left: 38%; overflow: visible; position: absolute; top: 38%; width: 17%; }",
	".framer-uPH7v .framer-fvs33a { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 200px); left: 38%; overflow: visible; position: absolute; top: 63%; width: 17%; }",
	".framer-uPH7v .framer-1fp2l5q { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 200px); left: 63%; overflow: visible; position: absolute; top: 38%; width: 17%; }",
	".framer-uPH7v .framer-184nf98 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 200px); left: 63%; overflow: visible; position: absolute; top: 63%; width: 17%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-uPH7v.framer-1f52rmj { gap: 0px; } .framer-uPH7v.framer-1f52rmj > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-uPH7v.framer-1f52rmj > :first-child { margin-left: 0px; } .framer-uPH7v.framer-1f52rmj > :last-child { margin-right: 0px; } }",
	".framer-uPH7v.framer-v-1dnuw6x .framer-fvs33a, .framer-uPH7v.framer-v-1dnuw6x .framer-184nf98 { aspect-ratio: unset; height: 3px; left: calc(50.00000000000002% - 50% / 2); top: calc(50.00000000000002% - 3px / 2); width: 50%; }",
];
var FramerrXMu4ZdSr = withCSS(Component, css, "framer-uPH7v");
var stdin_default = FramerrXMu4ZdSr;
FramerrXMu4ZdSr.displayName = "Cross Icon";
FramerrXMu4ZdSr.defaultProps = {
	height: 200,
	width: 200,
};
addPropertyControls(FramerrXMu4ZdSr, {
	variant: {
		options: ["X165QcoAj", "FRgnkpAWf"],
		optionTitles: ["Closed", "Open"],
		title: "Variant",
		type: ControlType.Enum,
	},
	kfdTaiDBR: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FramerrXMu4ZdSr,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:cross-icon
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "FRgnkpAWf",
	xl: "X165QcoAj",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0ab435b455d76c767a5dea9600bc5786a15f10b45126633827329afa7ac48a86"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CrossIconFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0ab435b455d76c767a5dea9600bc5786a15f10b45126633827329afa7ac48a86"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var cross_icon_default = ComponentWithRoot;
export { cross_icon_default as default };
