// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0ab435b455d76c76 "Eventis (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-N4CNHBNY.js";
import { className, css, fonts } from "./chunks/chunk-545RPIJJ.js";
import { Icon } from "./chunks/chunk-BTSBQWPZ.js";
import { routes } from "./chunks/chunk-MNEP7H2N.js";

// virtual:footer
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Footer-KFKc.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var PhosphorFonts = getFonts(Icon);
var MenuButtonFonts = getFonts(stdin_default);
var cycleOrder = ["wPhxp_N54", "id6A3sazA", "tqIYs2WdA"];
var serializationHash = "framer-RYOK6";
var variantClassNames = {
	id6A3sazA: "framer-v-ivq5hq",
	tqIYs2WdA: "framer-v-rlmk81",
	wPhxp_N54: "framer-v-1el6i8r",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "wPhxp_N54",
	Phone: "tqIYs2WdA",
	Tablet: "id6A3sazA",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "wPhxp_N54",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "wPhxp_N54",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.footer
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1el6i8r",
							className2,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"wPhxp_N54"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-440020f8-b9e1-49ea-9687-1ea12b43b3de, rgb(0, 0, 0))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								id6A3sazA: {
									"data-framer-name": "Tablet",
								},
								tqIYs2WdA: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 578,
								intrinsicWidth: 965.5,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										(componentViewport?.height || 610) -
										409.5,
								),
								pixelHeight: 1156,
								pixelWidth: 1931,
								sizes: componentViewport?.width || "100vw",
								src: "https://framerusercontent.com/images/pSSINVOSMIf4PhqxNRckBByjw.webp?scale-down-to=1024&width=1931&height=1156",
								srcSet:
									"https://framerusercontent.com/images/pSSINVOSMIf4PhqxNRckBByjw.webp?scale-down-to=512&width=1931&height=1156 512w,https://framerusercontent.com/images/pSSINVOSMIf4PhqxNRckBByjw.webp?scale-down-to=1024&width=1931&height=1156 1024w,https://framerusercontent.com/images/pSSINVOSMIf4PhqxNRckBByjw.webp?width=1931&height=1156 1931w",
							}}
							className={"framer-3zho6a"}
							data-framer-name={"Ai summit bg"}
							layoutDependency={layoutDependency}
							layoutId={"hkCxCIMwV"}
							style={{
								mask: "linear-gradient(0deg, rgba(0,0,0,1) 45.66744087837838%, rgba(0,0,0,0) 100%) add",
								WebkitMask:
									"linear-gradient(0deg, rgba(0,0,0,1) 45.66744087837838%, rgba(0,0,0,0) 100%) add",
							}}
							{...addPropertyOverrides(
								{
									id6A3sazA: {
										background: {
											alt: "",
											fit: "fill",
											intrinsicHeight: 578,
											intrinsicWidth: 965.5,
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													(componentViewport?.height || 700) -
													409.5,
											),
											pixelHeight: 1156,
											pixelWidth: 1931,
											sizes: componentViewport?.width || "100vw",
											src: "https://framerusercontent.com/images/pSSINVOSMIf4PhqxNRckBByjw.webp?scale-down-to=1024&width=1931&height=1156",
											srcSet:
												"https://framerusercontent.com/images/pSSINVOSMIf4PhqxNRckBByjw.webp?scale-down-to=512&width=1931&height=1156 512w,https://framerusercontent.com/images/pSSINVOSMIf4PhqxNRckBByjw.webp?scale-down-to=1024&width=1931&height=1156 1024w,https://framerusercontent.com/images/pSSINVOSMIf4PhqxNRckBByjw.webp?width=1931&height=1156 1931w",
										},
									},
									tqIYs2WdA: {
										background: {
											alt: "",
											fit: "fill",
											intrinsicHeight: 578,
											intrinsicWidth: 965.5,
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													(componentViewport?.height || 675) -
													409.5,
											),
											pixelHeight: 1156,
											pixelWidth: 1931,
											sizes: componentViewport?.width || "100vw",
											src: "https://framerusercontent.com/images/pSSINVOSMIf4PhqxNRckBByjw.webp?scale-down-to=1024&width=1931&height=1156",
											srcSet:
												"https://framerusercontent.com/images/pSSINVOSMIf4PhqxNRckBByjw.webp?scale-down-to=512&width=1931&height=1156 512w,https://framerusercontent.com/images/pSSINVOSMIf4PhqxNRckBByjw.webp?scale-down-to=1024&width=1931&height=1156 1024w,https://framerusercontent.com/images/pSSINVOSMIf4PhqxNRckBByjw.webp?width=1931&height=1156 1931w",
										},
									},
								},
								baseVariant,
								gestureVariant,
							)}
						/>
						<motion.div
							className={"framer-sdeuni"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"M7jgwSYWO"}
						>
							<motion.div
								className={"framer-nmj9fc"}
								data-framer-name={"Top"}
								layoutDependency={layoutDependency}
								layoutId={"vg5LIymMu"}
							>
								<motion.div
									className={"framer-5zv9q1"}
									data-framer-name={"Social Connects"}
									layoutDependency={layoutDependency}
									layoutId={"uTnYobCKl"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-17tcu0s"}
										data-framer-name={"Social"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"BCq3W8DGS"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-c465f8c5-7fa9-436d-b203-2cb129c31fb1, rgb(237, 237, 237))",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-dsr0r"}
												data-styles-preset={"Erxl6HnxD"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-c465f8c5-7fa9-436d-b203-2cb129c31fb1, rgb(237, 237, 237)))",
												}}
											>
												{"Social "}
											</motion.p>
										</React.Fragment>
									</RichText>
									<motion.div
										className={"framer-1dhn2g1"}
										data-framer-name={"Links"}
										layoutDependency={layoutDependency}
										layoutId={"xuy1q_RhM"}
									>
										<Link
											href={"www.facebook.com"}
											motionChild={true}
											nodeId={"fBt8qt1cO"}
											scopeId={"Kjfh2RU4w"}
										>
											<motion.a
												className={"framer-1p7sii6 framer-1rznr4h"}
												data-framer-name={"Facebook"}
												layoutDependency={layoutDependency}
												layoutId={"fBt8qt1cO"}
												style={{
													borderBottomLeftRadius: "100%",
													borderBottomRightRadius: "100%",
													borderTopLeftRadius: "100%",
													borderTopRightRadius: "100%",
												}}
											>
												<ComponentViewportProvider>
													<SmartComponentScopedContainer
														className={"framer-1q9j6t2-container"}
														isAuthoredByUser={true}
														isModuleExternal={true}
														layoutDependency={layoutDependency}
														layoutId={"rHs0Wn69r-container"}
														nodeId={"rHs0Wn69r"}
														rendersWithMotion={true}
														scopeId={"Kjfh2RU4w"}
													>
														<Icon
															color={
																"var(--token-c465f8c5-7fa9-436d-b203-2cb129c31fb1, rgb(237, 237, 237))"
															}
															height={"100%"}
															iconSearch={"House"}
															iconSelection={"FacebookLogo"}
															id={"rHs0Wn69r"}
															layoutId={"rHs0Wn69r"}
															mirrored={false}
															selectByList={true}
															style={{
																height: "100%",
																width: "100%",
															}}
															weight={"regular"}
															width={"100%"}
														/>
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											</motion.a>
										</Link>
										<Link
											href={"https://www.instagram.com/jitu.ux/"}
											motionChild={true}
											nodeId={"Af9TJ9ai3"}
											openInNewTab={true}
											scopeId={"Kjfh2RU4w"}
										>
											<motion.a
												className={"framer-zdafop framer-1rznr4h"}
												data-framer-name={"Instagram"}
												layoutDependency={layoutDependency}
												layoutId={"Af9TJ9ai3"}
												style={{
													borderBottomLeftRadius: "100%",
													borderBottomRightRadius: "100%",
													borderTopLeftRadius: "100%",
													borderTopRightRadius: "100%",
												}}
											>
												<ComponentViewportProvider>
													<SmartComponentScopedContainer
														className={"framer-meo1sm-container"}
														isAuthoredByUser={true}
														isModuleExternal={true}
														layoutDependency={layoutDependency}
														layoutId={"GJ_wRRlO8-container"}
														nodeId={"GJ_wRRlO8"}
														rendersWithMotion={true}
														scopeId={"Kjfh2RU4w"}
													>
														<Icon
															color={
																"var(--token-c465f8c5-7fa9-436d-b203-2cb129c31fb1, rgb(237, 237, 237))"
															}
															height={"100%"}
															iconSearch={"House"}
															iconSelection={"InstagramLogo"}
															id={"GJ_wRRlO8"}
															layoutId={"GJ_wRRlO8"}
															mirrored={false}
															selectByList={true}
															style={{
																height: "100%",
																width: "100%",
															}}
															weight={"regular"}
															width={"100%"}
														/>
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											</motion.a>
										</Link>
										<Link
											href={"www.linkedin.com/in/jitendra-raut/"}
											motionChild={true}
											nodeId={"vb_Kha63O"}
											openInNewTab={true}
											scopeId={"Kjfh2RU4w"}
										>
											<motion.a
												className={"framer-nwu7er framer-1rznr4h"}
												data-framer-name={"Linkedin"}
												layoutDependency={layoutDependency}
												layoutId={"vb_Kha63O"}
												style={{
													borderBottomLeftRadius: "100%",
													borderBottomRightRadius: "100%",
													borderTopLeftRadius: "100%",
													borderTopRightRadius: "100%",
												}}
											>
												<ComponentViewportProvider>
													<SmartComponentScopedContainer
														className={"framer-mwybfh-container"}
														isAuthoredByUser={true}
														isModuleExternal={true}
														layoutDependency={layoutDependency}
														layoutId={"gXS7pziBu-container"}
														nodeId={"gXS7pziBu"}
														rendersWithMotion={true}
														scopeId={"Kjfh2RU4w"}
													>
														<Icon
															color={
																"var(--token-c465f8c5-7fa9-436d-b203-2cb129c31fb1, rgb(237, 237, 237))"
															}
															height={"100%"}
															iconSearch={"House"}
															iconSelection={"LinkedinLogo"}
															id={"gXS7pziBu"}
															layoutId={"gXS7pziBu"}
															mirrored={false}
															selectByList={true}
															style={{
																height: "100%",
																width: "100%",
															}}
															weight={"regular"}
															width={"100%"}
														/>
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											</motion.a>
										</Link>
										<Link
											href={"https://x.com/jituux"}
											motionChild={true}
											nodeId={"LAcNdKAb6"}
											openInNewTab={true}
											scopeId={"Kjfh2RU4w"}
										>
											<motion.a
												className={"framer-1l4gi3g framer-1rznr4h"}
												data-framer-name={"X"}
												layoutDependency={layoutDependency}
												layoutId={"LAcNdKAb6"}
												style={{
													borderBottomLeftRadius: "100%",
													borderBottomRightRadius: "100%",
													borderTopLeftRadius: "100%",
													borderTopRightRadius: "100%",
												}}
											>
												<ComponentViewportProvider>
													<SmartComponentScopedContainer
														className={"framer-1p56u4x-container"}
														isAuthoredByUser={true}
														isModuleExternal={true}
														layoutDependency={layoutDependency}
														layoutId={"vA60MjdGM-container"}
														nodeId={"vA60MjdGM"}
														rendersWithMotion={true}
														scopeId={"Kjfh2RU4w"}
													>
														<Icon
															color={
																"var(--token-c465f8c5-7fa9-436d-b203-2cb129c31fb1, rgb(237, 237, 237))"
															}
															height={"100%"}
															iconSearch={"House"}
															iconSelection={"XLogo"}
															id={"vA60MjdGM"}
															layoutId={"vA60MjdGM"}
															mirrored={false}
															selectByList={true}
															style={{
																height: "100%",
																width: "100%",
															}}
															weight={"regular"}
															width={"100%"}
														/>
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											</motion.a>
										</Link>
									</motion.div>
								</motion.div>
								<motion.nav
									className={"framer-1a0e2lt"}
									data-framer-name={"Links"}
									layoutDependency={layoutDependency}
									layoutId={"GnLaUlAcp"}
								>
									<ResolveLinks
										links={[
											{
												href: {
													webPageId: "H5KkvzB6J",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "H5KkvzB6J",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "H5KkvzB6J",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks) => (
											<ComponentViewportProvider
												height={40}
												y={
													(componentViewport?.y || 0) +
													100 +
													(((componentViewport?.height || 610) - 100 - 614) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0 +
													138 +
													0
												}
												{...addPropertyOverrides(
													{
														id6A3sazA: {
															y:
																(componentViewport?.y || 0) +
																100 +
																(((componentViewport?.height || 700) -
																	100 -
																	766) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																242 +
																0,
														},
														tqIYs2WdA: {
															y: void 0,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-1679smr-container"}
													layoutDependency={layoutDependency}
													layoutId={"TTje7dStt-container"}
													nodeId={"TTje7dStt"}
													rendersWithMotion={true}
													scopeId={"Kjfh2RU4w"}
												>
													{_jsx(stdin_default, {
														ac4JHN6Mf: resolvedLinks[0],
														FXv52DSLw: false,
														height: "100%",
														id: "TTje7dStt",
														layoutId: "TTje7dStt",
														variant: "NqmrBcKU0",
														width: "100%",
														Xg1a7VaWe: "Speakers",
														...addPropertyOverrides(
															{
																id6A3sazA: {
																	ac4JHN6Mf: resolvedLinks[1],
																},
																tqIYs2WdA: {
																	ac4JHN6Mf: resolvedLinks[2],
																	variant: "HK7rTO971",
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<ResolveLinks
										links={[
											{
												href: {
													webPageId: "Aw1bp1qBS",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "Aw1bp1qBS",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "Aw1bp1qBS",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks1) => (
											<ComponentViewportProvider
												height={40}
												y={
													(componentViewport?.y || 0) +
													100 +
													(((componentViewport?.height || 610) - 100 - 614) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0 +
													138 +
													0
												}
												{...addPropertyOverrides(
													{
														id6A3sazA: {
															y:
																(componentViewport?.y || 0) +
																100 +
																(((componentViewport?.height || 700) -
																	100 -
																	766) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																242 +
																0,
														},
														tqIYs2WdA: {
															y: void 0,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-17ks4fl-container"}
													layoutDependency={layoutDependency}
													layoutId={"HwTP9JVSc-container"}
													nodeId={"HwTP9JVSc"}
													rendersWithMotion={true}
													scopeId={"Kjfh2RU4w"}
												>
													{_jsx(stdin_default, {
														ac4JHN6Mf: resolvedLinks1[0],
														FXv52DSLw: false,
														height: "100%",
														id: "HwTP9JVSc",
														layoutId: "HwTP9JVSc",
														variant: "NqmrBcKU0",
														width: "100%",
														Xg1a7VaWe: "Agenda",
														...addPropertyOverrides(
															{
																id6A3sazA: {
																	ac4JHN6Mf: resolvedLinks1[1],
																},
																tqIYs2WdA: {
																	ac4JHN6Mf: resolvedLinks1[2],
																	variant: "HK7rTO971",
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<ResolveLinks
										links={[
											{
												href: {
													webPageId: "vrrKLizBH",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "vrrKLizBH",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "vrrKLizBH",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks2) => (
											<ComponentViewportProvider
												height={40}
												y={
													(componentViewport?.y || 0) +
													100 +
													(((componentViewport?.height || 610) - 100 - 614) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0 +
													138 +
													0
												}
												{...addPropertyOverrides(
													{
														id6A3sazA: {
															y:
																(componentViewport?.y || 0) +
																100 +
																(((componentViewport?.height || 700) -
																	100 -
																	766) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																242 +
																0,
														},
														tqIYs2WdA: {
															y: void 0,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-10a3fdy-container"}
													layoutDependency={layoutDependency}
													layoutId={"MJWIUgM6J-container"}
													nodeId={"MJWIUgM6J"}
													rendersWithMotion={true}
													scopeId={"Kjfh2RU4w"}
												>
													{_jsx(stdin_default, {
														ac4JHN6Mf: resolvedLinks2[0],
														FXv52DSLw: false,
														height: "100%",
														id: "MJWIUgM6J",
														layoutId: "MJWIUgM6J",
														variant: "NqmrBcKU0",
														width: "100%",
														Xg1a7VaWe: "Venue",
														...addPropertyOverrides(
															{
																id6A3sazA: {
																	ac4JHN6Mf: resolvedLinks2[1],
																},
																tqIYs2WdA: {
																	ac4JHN6Mf: resolvedLinks2[2],
																	variant: "HK7rTO971",
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<ResolveLinks
										links={[
											{
												href: {
													webPageId: "tgsKZLLek",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "tgsKZLLek",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "tgsKZLLek",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks3) => (
											<ComponentViewportProvider
												height={40}
												y={
													(componentViewport?.y || 0) +
													100 +
													(((componentViewport?.height || 610) - 100 - 614) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0 +
													138 +
													0
												}
												{...addPropertyOverrides(
													{
														id6A3sazA: {
															y:
																(componentViewport?.y || 0) +
																100 +
																(((componentViewport?.height || 700) -
																	100 -
																	766) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																242 +
																0,
														},
														tqIYs2WdA: {
															y: void 0,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-o9y6lc-container"}
													layoutDependency={layoutDependency}
													layoutId={"LxQ7e6tvd-container"}
													nodeId={"LxQ7e6tvd"}
													rendersWithMotion={true}
													scopeId={"Kjfh2RU4w"}
												>
													{_jsx(stdin_default, {
														ac4JHN6Mf: resolvedLinks3[0],
														FXv52DSLw: false,
														height: "100%",
														id: "LxQ7e6tvd",
														layoutId: "LxQ7e6tvd",
														variant: "NqmrBcKU0",
														width: "100%",
														Xg1a7VaWe: "Contact",
														...addPropertyOverrides(
															{
																id6A3sazA: {
																	ac4JHN6Mf: resolvedLinks3[1],
																},
																tqIYs2WdA: {
																	ac4JHN6Mf: resolvedLinks3[2],
																	variant: "HK7rTO971",
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
								</motion.nav>
							</motion.div>
							<motion.div
								className={"framer-1nrybkz"}
								data-border={true}
								data-framer-name={"Bottom"}
								layoutDependency={layoutDependency}
								layoutId={"X4eKfxf8D"}
								style={{
									"--border-bottom-width": "0px",
									"--border-color":
										"var(--token-9a7303fe-2324-4aa1-bbd4-e1f1d449de82, rgba(255, 255, 255, 0.12))",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-style": "solid",
									"--border-top-width": "1px",
								}}
							>
								<motion.div
									className={"framer-dvwnx7"}
									data-framer-name={"Empty"}
									layoutDependency={layoutDependency}
									layoutId={"FR952dISU"}
								/>
								<motion.div
									className={"framer-1xctxok"}
									data-framer-name={"Content"}
									layoutDependency={layoutDependency}
									layoutId={"DUF7x0Xin"}
								>
									<motion.div
										className={"framer-spf60w"}
										data-framer-name={"Copyright"}
										layoutDependency={layoutDependency}
										layoutId={"gyzyKiVeI"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1ie1jya"}
											data-framer-name={
												"All copyrights are reserve at @Karyakram"
											}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"uPHYALJEN"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-c465f8c5-7fa9-436d-b203-2cb129c31fb1, rgb(237, 237, 237))",
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-dsr0r"}
													data-styles-preset={"Erxl6HnxD"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-c465f8c5-7fa9-436d-b203-2cb129c31fb1, rgb(237, 237, 237)))",
													}}
												>
													{"All copyrights @eventis"}
												</motion.p>
											</React.Fragment>
										</RichText>
										<Link
											href={{
												webPageId: "LZKCF9PiE",
											}}
											motionChild={true}
											nodeId={"D8srKmfVc"}
											openInNewTab={true}
											scopeId={"Kjfh2RU4w"}
										>
											<motion.a
												className={"framer-b79ppf framer-1rznr4h"}
												data-framer-name={"Link"}
												layoutDependency={layoutDependency}
												layoutId={"D8srKmfVc"}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-18tis13"}
													data-framer-name={
														"Design By Jitu Raut @remixframer.com"
													}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"PSdKlmDFG"}
													style={{
														"--extracted-r6o4lv":
															"var(--token-c465f8c5-7fa9-436d-b203-2cb129c31fb1, rgb(237, 237, 237))",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-dsr0r"}
															data-styles-preset={"Erxl6HnxD"}
															style={{
																"--framer-text-alignment": "right",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-c465f8c5-7fa9-436d-b203-2cb129c31fb1, rgb(237, 237, 237)))",
															}}
														>
															{"Terms and Conditions"}
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.a>
										</Link>
									</motion.div>
									<Link
										href={"https://fremix.design/"}
										motionChild={true}
										nodeId={"VnY_4Gpse"}
										openInNewTab={true}
										scopeId={"Kjfh2RU4w"}
									>
										<motion.a
											className={"framer-1n7mxh0 framer-1rznr4h"}
											data-framer-name={"Link"}
											layoutDependency={layoutDependency}
											layoutId={"VnY_4Gpse"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1q54pl8"}
												data-framer-name={
													"Design By Jitu Raut @remixframer.com"
												}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"hypIuPAnj"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-c465f8c5-7fa9-436d-b203-2cb129c31fb1, rgb(237, 237, 237))",
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
												{...addPropertyOverrides(
													{
														tqIYs2WdA: {
															children: (
																<React.Fragment>
																	<motion.p
																		className={"framer-styles-preset-dsr0r"}
																		data-styles-preset={"Erxl6HnxD"}
																		style={{
																			"--framer-text-alignment": "left",
																			"--framer-text-color":
																				"var(--extracted-r6o4lv, var(--token-c465f8c5-7fa9-436d-b203-2cb129c31fb1, rgb(237, 237, 237)))",
																		}}
																	>
																		{"Designed By Jitu Raut  @fremix.design"}
																	</motion.p>
																</React.Fragment>
															),
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-dsr0r"}
														data-styles-preset={"Erxl6HnxD"}
														style={{
															"--framer-text-alignment": "right",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-c465f8c5-7fa9-436d-b203-2cb129c31fb1, rgb(237, 237, 237)))",
														}}
													>
														{"Designed By Jitu Raut  @fremix.design"}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.a>
									</Link>
								</motion.div>
							</motion.div>
						</motion.div>
						<Image
							as={"figure"}
							background={{
								alt: "",
								fit: "fit",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										100 +
										(((componentViewport?.height || 610) - 100 - 614) / 2 +
											315 +
											108),
								),
								pixelHeight: 319,
								pixelWidth: 2023,
								positionX: "center",
								positionY: "center",
								sizes: componentViewport?.width || "100vw",
								src: "https://framerusercontent.com/images/1BHox7UUEVMJHfAPN4qPh5r4o.svg?width=2023&height=319",
								srcSet:
									"https://framerusercontent.com/images/1BHox7UUEVMJHfAPN4qPh5r4o.svg?scale-down-to=512&width=2023&height=319 512w,https://framerusercontent.com/images/1BHox7UUEVMJHfAPN4qPh5r4o.svg?scale-down-to=1024&width=2023&height=319 1024w,https://framerusercontent.com/images/1BHox7UUEVMJHfAPN4qPh5r4o.svg?width=2023&height=319 2023w",
							}}
							className={"framer-16fyxtb"}
							layoutDependency={layoutDependency}
							layoutId={"HxkbLftuB"}
							style={{
								mask: "linear-gradient(353deg, rgba(0,0,0,0) 15%, rgba(0, 0, 0, 0.49) 32%, rgba(0,0,0,1) 75%) add",
								WebkitMask:
									"linear-gradient(353deg, rgba(0,0,0,0) 15%, rgba(0, 0, 0, 0.49) 32%, rgba(0,0,0,1) 75%) add",
							}}
							{...addPropertyOverrides(
								{
									id6A3sazA: {
										background: {
											alt: "",
											fit: "fit",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													100 +
													(((componentViewport?.height || 700) - 100 - 766) /
														2 +
														467 +
														108),
											),
											pixelHeight: 319,
											pixelWidth: 2023,
											positionX: "center",
											positionY: "center",
											sizes: componentViewport?.width || "100vw",
											src: "https://framerusercontent.com/images/1BHox7UUEVMJHfAPN4qPh5r4o.svg?width=2023&height=319",
											srcSet:
												"https://framerusercontent.com/images/1BHox7UUEVMJHfAPN4qPh5r4o.svg?scale-down-to=512&width=2023&height=319 512w,https://framerusercontent.com/images/1BHox7UUEVMJHfAPN4qPh5r4o.svg?scale-down-to=1024&width=2023&height=319 1024w,https://framerusercontent.com/images/1BHox7UUEVMJHfAPN4qPh5r4o.svg?width=2023&height=319 2023w",
										},
									},
									tqIYs2WdA: {
										background: {
											alt: "",
											fit: "fit",
											pixelHeight: 319,
											pixelWidth: 2023,
											positionX: "center",
											positionY: "center",
											sizes: componentViewport?.width || "100vw",
											src: "https://framerusercontent.com/images/1BHox7UUEVMJHfAPN4qPh5r4o.svg?width=2023&height=319",
											srcSet:
												"https://framerusercontent.com/images/1BHox7UUEVMJHfAPN4qPh5r4o.svg?scale-down-to=512&width=2023&height=319 512w,https://framerusercontent.com/images/1BHox7UUEVMJHfAPN4qPh5r4o.svg?scale-down-to=1024&width=2023&height=319 1024w,https://framerusercontent.com/images/1BHox7UUEVMJHfAPN4qPh5r4o.svg?width=2023&height=319 2023w",
										},
									},
								},
								baseVariant,
								gestureVariant,
							)}
						/>
					</motion.footer>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-RYOK6.framer-1rznr4h, .framer-RYOK6 .framer-1rznr4h { display: block; }",
	".framer-RYOK6.framer-1el6i8r { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 108px; height: min-content; justify-content: center; overflow: hidden; padding: 100px 0px 0px 0px; position: relative; width: 1200px; }",
	".framer-RYOK6 .framer-3zho6a { bottom: -20px; flex: none; height: 430px; left: calc(50.00000000000002% - 100% / 2); overflow: visible; position: absolute; width: 100%; z-index: 0; }",
	".framer-RYOK6 .framer-sdeuni { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 72px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-RYOK6 .framer-nmj9fc { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: center; max-width: 1440px; overflow: hidden; padding: 0px 40px 0px 40px; position: relative; width: 100%; }",
	".framer-RYOK6 .framer-5zv9q1 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-RYOK6 .framer-17tcu0s { align-self: stretch; flex: none; height: auto; position: relative; white-space: pre-wrap; width: auto; word-break: break-word; word-wrap: break-word; }",
	".framer-RYOK6 .framer-1dhn2g1 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-RYOK6 .framer-1p7sii6, .framer-RYOK6 .framer-zdafop, .framer-RYOK6 .framer-nwu7er, .framer-RYOK6 .framer-1l4gi3g { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 40px); justify-content: center; padding: 0px; position: relative; text-decoration: none; width: 40px; }",
	".framer-RYOK6 .framer-1q9j6t2-container, .framer-RYOK6 .framer-meo1sm-container, .framer-RYOK6 .framer-mwybfh-container, .framer-RYOK6 .framer-1p56u4x-container { flex: 1 0 0px; height: 100%; position: relative; width: 1px; }",
	".framer-RYOK6 .framer-1a0e2lt { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-RYOK6 .framer-1679smr-container, .framer-RYOK6 .framer-17ks4fl-container, .framer-RYOK6 .framer-10a3fdy-container, .framer-RYOK6 .framer-o9y6lc-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-RYOK6 .framer-1nrybkz { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-RYOK6 .framer-dvwnx7 { flex: none; height: 1px; overflow: hidden; position: relative; width: 100%; }",
	".framer-RYOK6 .framer-1xctxok { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: center; max-width: 1440px; overflow: hidden; padding: 0px 40px 0px 40px; position: relative; width: 100%; }",
	".framer-RYOK6 .framer-spf60w { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 38px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-RYOK6 .framer-1ie1jya, .framer-RYOK6 .framer-18tis13, .framer-RYOK6 .framer-1q54pl8 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-RYOK6 .framer-b79ppf, .framer-RYOK6 .framer-1n7mxh0 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-end; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-RYOK6 .framer-16fyxtb { aspect-ratio: 6.282722513089006 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 191px); overflow: visible; position: relative; width: 100%; }",
	".framer-RYOK6.framer-v-ivq5hq.framer-1el6i8r { width: 810px; }",
	".framer-RYOK6.framer-v-ivq5hq .framer-nmj9fc { align-content: flex-start; align-items: flex-start; flex-direction: column; }",
	".framer-RYOK6.framer-v-ivq5hq .framer-1a0e2lt { flex: none; justify-content: flex-start; width: 100%; }",
	".framer-RYOK6.framer-v-ivq5hq .framer-1xctxok { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 24px; }",
	".framer-RYOK6.framer-v-ivq5hq .framer-spf60w { flex: none; width: 100%; }",
	".framer-RYOK6.framer-v-ivq5hq .framer-16fyxtb { height: var(--framer-aspect-ratio-supported, 129px); }",
	".framer-RYOK6.framer-v-rlmk81.framer-1el6i8r { gap: 96px; padding: 84px 0px 0px 0px; width: 390px; }",
	".framer-RYOK6.framer-v-rlmk81 .framer-sdeuni { align-content: flex-start; align-items: flex-start; }",
	".framer-RYOK6.framer-v-rlmk81 .framer-nmj9fc { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 48px; padding: 0px 20px 0px 20px; }",
	".framer-RYOK6.framer-v-rlmk81 .framer-1dhn2g1 { gap: 16px; }",
	".framer-RYOK6.framer-v-rlmk81 .framer-1p7sii6, .framer-RYOK6.framer-v-rlmk81 .framer-zdafop, .framer-RYOK6.framer-v-rlmk81 .framer-nwu7er, .framer-RYOK6.framer-v-rlmk81 .framer-1l4gi3g { height: var(--framer-aspect-ratio-supported, 32px); width: 32px; }",
	".framer-RYOK6.framer-v-rlmk81 .framer-1a0e2lt { align-content: flex-start; align-items: flex-start; flex: none; flex-wrap: wrap; justify-content: flex-start; width: 100%; }",
	".framer-RYOK6.framer-v-rlmk81 .framer-1xctxok { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 24px; padding: 0px 20px 0px 20px; }",
	".framer-RYOK6.framer-v-rlmk81 .framer-spf60w { align-content: flex-start; align-items: flex-start; flex: none; flex-direction: column; gap: 20px; width: 100%; }",
	".framer-RYOK6.framer-v-rlmk81 .framer-1n7mxh0 { width: 100%; }",
	".framer-RYOK6.framer-v-rlmk81 .framer-1q54pl8 { flex: 1 0 0px; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-RYOK6.framer-v-rlmk81 .framer-16fyxtb { height: var(--framer-aspect-ratio-supported, 62px); }",
	...css,
	'.framer-RYOK6[data-border="true"]::after, .framer-RYOK6 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerKjfh2RU4w = withCSS(Component, css2, "framer-RYOK6");
var stdin_default2 = FramerKjfh2RU4w;
FramerKjfh2RU4w.displayName = "Footer";
FramerKjfh2RU4w.defaultProps = {
	height: 610,
	width: 1200,
};
addPropertyControls(FramerKjfh2RU4w, {
	variant: {
		options: ["wPhxp_N54", "id6A3sazA", "tqIYs2WdA"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerKjfh2RU4w,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PhosphorFonts,
		...MenuButtonFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:footer
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "tqIYs2WdA",
	md: "id6A3sazA",
	xl: "wPhxp_N54",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0ab435b455d76c767a5dea9600bc5786a15f10b45126633827329afa7ac48a86"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0ab435b455d76c767a5dea9600bc5786a15f10b45126633827329afa7ac48a86"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var footer_default = ComponentWithRoot;
export { footer_default as default };
