// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0ab435b455d76c76 "Eventis (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * name?: string // Name
 * designation?: string // Designation
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-545RPIJJ.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-5D5Y4IKK.js";
import { routes } from "./chunks/chunk-MNEP7H2N.js";

// virtual:guest-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Guest-Card-YIr0.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-FimtX";
var variantClassNames = {
	X2p9TaKiJ: "framer-v-1git8e4",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ designation, height, id, image, name1, width, ...props }) => {
	return {
		...props,
		ls6h6WSVt: image ??
			props.ls6h6WSVt ?? {
				pixelHeight: 1200,
				pixelWidth: 1200,
				src: "https://framerusercontent.com/images/dlhgx3fMLQZlK7XF8F8pg5OGE.png?scale-down-to=512",
				srcSet:
					"https://framerusercontent.com/images/dlhgx3fMLQZlK7XF8F8pg5OGE.png?scale-down-to=512 512w,https://framerusercontent.com/images/dlhgx3fMLQZlK7XF8F8pg5OGE.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/dlhgx3fMLQZlK7XF8F8pg5OGE.png 1200w",
			},
		QmtD_b0ER: name1 ?? props.QmtD_b0ER ?? "Jitendra Raut",
		XkNCZnR0o: designation ?? props.XkNCZnR0o ?? "Founder of Windesign Labs",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		ls6h6WSVt,
		QmtD_b0ER,
		XkNCZnR0o,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "X2p9TaKiJ",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1git8e4",
							className3,
							classNames,
						)}
						data-framer-name={"Guest Card"}
						layoutDependency={layoutDependency}
						layoutId={"X2p9TaKiJ"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<Image
							as={"figure"}
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										(0 + ((componentViewport?.height || 122) - 0 - 122) / 2),
								),
								sizes: "117px",
								...toResponsiveImage(ls6h6WSVt),
							}}
							className={"framer-7rs5ed"}
							data-framer-name={"Image"}
							layoutDependency={layoutDependency}
							layoutId={"V9dp5iaMA"}
							style={{
								borderBottomLeftRadius: 24,
								borderBottomRightRadius: 24,
								borderTopLeftRadius: 24,
								borderTopRightRadius: 24,
							}}
						/>
						<motion.div
							className={"framer-14xlkuf"}
							data-framer-name={"Profile"}
							layoutDependency={layoutDependency}
							layoutId={"ojc8ImxBR"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-fh90zc"}
								data-framer-name={"Jitendra Raut"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"kVQGwHUu1"}
								style={{
									"--extracted-1eung3n":
										"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={QmtD_b0ER}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h4
										className={"framer-styles-preset-luad1x"}
										data-styles-preset={"QrpSGcou5"}
										style={{
											"--framer-text-color":
												"var(--extracted-1eung3n, var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255)))",
										}}
									>
										{"Jitendra Raut"}
									</motion.h4>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1q7gem2"}
								data-framer-name={"Founder of Windesign Labs"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"iNNuAAbIn"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-80ffe7cf-9d09-4fa3-9c39-3c4b6492f37f, rgb(191, 191, 191))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={XkNCZnR0o}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-dsr0r"}
										data-styles-preset={"Erxl6HnxD"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-80ffe7cf-9d09-4fa3-9c39-3c4b6492f37f, rgb(191, 191, 191)))",
										}}
									>
										{"Founder of Windesign Labs"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-FimtX.framer-1h6uvzd, .framer-FimtX .framer-1h6uvzd { display: block; }",
	".framer-FimtX.framer-1git8e4 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 22px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 306px; }",
	".framer-FimtX .framer-7rs5ed { aspect-ratio: 0.9586776859504132 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 122px); position: relative; width: 117px; }",
	".framer-FimtX .framer-14xlkuf { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-FimtX .framer-fh90zc, .framer-FimtX .framer-1q7gem2 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	...css2,
	...css,
];
var FramerpguzL4NbK = withCSS(Component, css3, "framer-FimtX");
var stdin_default = FramerpguzL4NbK;
FramerpguzL4NbK.displayName = "Guest Card";
FramerpguzL4NbK.defaultProps = {
	height: 122,
	width: 306,
};
addPropertyControls(FramerpguzL4NbK, {
	ls6h6WSVt: {
		__defaultAssetReference:
			"data:framer/asset-reference,dlhgx3fMLQZlK7XF8F8pg5OGE.png?originalFilename=QmeMZG4MBNSedvw1VKfvSaa4gtvjT5ZrQFj9UWxyFL7ubm%3Fauto%3Dformat%26h%3D1200.png&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	QmtD_b0ER: {
		defaultValue: "Jitendra Raut",
		displayTextArea: false,
		title: "Name",
		type: ControlType.String,
	},
	XkNCZnR0o: {
		defaultValue: "Founder of Windesign Labs",
		displayTextArea: false,
		title: "Designation",
		type: ControlType.String,
	},
});
addFonts(
	FramerpguzL4NbK,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:guest-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0ab435b455d76c767a5dea9600bc5786a15f10b45126633827329afa7ac48a86"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders GuestCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0ab435b455d76c767a5dea9600bc5786a15f10b45126633827329afa7ac48a86"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var guest_card_default = ComponentWithRoot;
export { guest_card_default as default };
