// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0ab435b455d76c76 "Eventis (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet Close' | 'Tablet Open' | 'Phone Close' | 'Phone Open' | 'Desktop Scroll' | 'Tablet Scroll' | 'Phone Scroll' // Variant
 * link?: string // Link
}} Props

 */
import { stdin_default as stdin_default2 } from "./chunks/chunk-KQVZIODJ.js";
import "./chunks/chunk-DD6C4KVC.js";
import { stdin_default } from "./chunks/chunk-N4CNHBNY.js";
import "./chunks/chunk-545RPIJJ.js";
import "./chunks/chunk-BTSBQWPZ.js";
import { routes } from "./chunks/chunk-MNEP7H2N.js";

// virtual:navigation
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Navigation-u9RE9.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	ResolveLinks,
	SmartComponentScopedContainer,
	useActiveVariantCallback as useActiveVariantCallback2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useRouter,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/RapqBz4jjaVuNwEu3oAJ/BUyysG3yMB2gKoAwhMBU/rXMu4ZdSr.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["X165QcoAj", "FRgnkpAWf"];
var serializationHash = "framer-uPH7v";
var variantClassNames = {
	FRgnkpAWf: "framer-v-1dnuw6x",
	X165QcoAj: "framer-v-1f52rmj",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Closed: "X165QcoAj",
	Open: "FRgnkpAWf",
};
var getProps = ({ click, height, id, width, ...props }) => {
	return {
		...props,
		kfdTaiDBR: click ?? props.kfdTaiDBR,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "X165QcoAj",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, kfdTaiDBR, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "X165QcoAj",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTaphtvfb2 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (kfdTaiDBR) {
			const res = await kfdTaiDBR(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1f52rmj",
							className,
							classNames,
						)}
						data-framer-name={"Closed"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"X165QcoAj"}
						onTap={onTaphtvfb2}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								FRgnkpAWf: {
									"data-framer-name": "Open",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-d4n7ab"}
							data-framer-name={"Menu"}
							layoutDependency={layoutDependency}
							layoutId={"GMaFMZaQF"}
							style={{
								borderBottomLeftRadius: 60,
								borderBottomRightRadius: 60,
								borderTopLeftRadius: 60,
								borderTopRightRadius: 60,
							}}
						>
							<motion.div
								className={"framer-1383mk6"}
								layoutDependency={layoutDependency}
								layoutId={"JiJbi8udO"}
								style={{
									backgroundColor:
										"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))",
									borderBottomLeftRadius: 3,
									borderBottomRightRadius: 3,
									borderTopLeftRadius: 3,
									borderTopRightRadius: 3,
									opacity: 1,
								}}
								transformTemplate={transformTemplate1}
								variants={{
									FRgnkpAWf: {
										opacity: 0,
									},
								}}
							/>
							<motion.div
								className={"framer-fvs33a"}
								layoutDependency={layoutDependency}
								layoutId={"TxpA7iGFa"}
								style={{
									backgroundColor:
										"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))",
									borderBottomLeftRadius: 3,
									borderBottomRightRadius: 3,
									borderTopLeftRadius: 3,
									borderTopRightRadius: 3,
									rotate: 0,
								}}
								transformTemplate={transformTemplate1}
								variants={{
									FRgnkpAWf: {
										rotate: 45,
									},
								}}
								{...addPropertyOverrides(
									{
										FRgnkpAWf: {
											transformTemplate: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
							<motion.div
								className={"framer-1fp2l5q"}
								layoutDependency={layoutDependency}
								layoutId={"YzWSebmew"}
								style={{
									backgroundColor:
										"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))",
									borderBottomLeftRadius: 3,
									borderBottomRightRadius: 3,
									borderTopLeftRadius: 3,
									borderTopRightRadius: 3,
									opacity: 1,
								}}
								transformTemplate={transformTemplate1}
								variants={{
									FRgnkpAWf: {
										opacity: 0,
									},
								}}
							/>
							<motion.div
								className={"framer-184nf98"}
								layoutDependency={layoutDependency}
								layoutId={"kmaODLDOo"}
								style={{
									backgroundColor:
										"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))",
									borderBottomLeftRadius: 3,
									borderBottomRightRadius: 3,
									borderTopLeftRadius: 3,
									borderTopRightRadius: 3,
									rotate: 0,
								}}
								transformTemplate={transformTemplate1}
								variants={{
									FRgnkpAWf: {
										rotate: -45,
									},
								}}
								{...addPropertyOverrides(
									{
										FRgnkpAWf: {
											transformTemplate: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-uPH7v.framer-a03djy, .framer-uPH7v .framer-a03djy { display: block; }",
	".framer-uPH7v.framer-1f52rmj { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-uPH7v .framer-d4n7ab { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 36px); overflow: hidden; position: relative; width: 36px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-uPH7v .framer-1383mk6 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 200px); left: 38%; overflow: visible; position: absolute; top: 38%; width: 17%; }",
	".framer-uPH7v .framer-fvs33a { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 200px); left: 38%; overflow: visible; position: absolute; top: 63%; width: 17%; }",
	".framer-uPH7v .framer-1fp2l5q { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 200px); left: 63%; overflow: visible; position: absolute; top: 38%; width: 17%; }",
	".framer-uPH7v .framer-184nf98 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 200px); left: 63%; overflow: visible; position: absolute; top: 63%; width: 17%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-uPH7v.framer-1f52rmj { gap: 0px; } .framer-uPH7v.framer-1f52rmj > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-uPH7v.framer-1f52rmj > :first-child { margin-left: 0px; } .framer-uPH7v.framer-1f52rmj > :last-child { margin-right: 0px; } }",
	".framer-uPH7v.framer-v-1dnuw6x .framer-fvs33a, .framer-uPH7v.framer-v-1dnuw6x .framer-184nf98 { aspect-ratio: unset; height: 3px; left: calc(50.00000000000002% - 50% / 2); top: calc(50.00000000000002% - 3px / 2); width: 50%; }",
];
var FramerrXMu4ZdSr = withCSS(Component, css, "framer-uPH7v");
var stdin_default3 = FramerrXMu4ZdSr;
FramerrXMu4ZdSr.displayName = "Cross Icon";
FramerrXMu4ZdSr.defaultProps = {
	height: 200,
	width: 200,
};
addPropertyControls(FramerrXMu4ZdSr, {
	variant: {
		options: ["X165QcoAj", "FRgnkpAWf"],
		optionTitles: ["Closed", "Open"],
		title: "Variant",
		type: ControlType.Enum,
	},
	kfdTaiDBR: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FramerrXMu4ZdSr,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framer.com/m/Navigation-u9RE9.js
var ButtonFonts = getFonts(stdin_default2);
var CrossIconFonts = getFonts(stdin_default3);
var MenuButtonFonts = getFonts(stdin_default);
var SmartComponentScopedContainerWithFXWithOptimizedAppearEffect =
	withOptimizedAppearEffect(withFX(SmartComponentScopedContainer));
var MotionNavWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion2.nav),
);
var cycleOrder2 = [
	"O8p5JbvBg",
	"MeTxynoL2",
	"avm8OLc_A",
	"ZMh3rRVPs",
	"tlHcUv3w4",
	"gfzXc5QXH",
	"vA5FUeUvu",
	"KMUe7lBtZ",
];
var serializationHash2 = "framer-Luar2";
var variantClassNames2 = {
	avm8OLc_A: "framer-v-15y03z2",
	gfzXc5QXH: "framer-v-8vgg4f",
	KMUe7lBtZ: "framer-v-wz6pu4",
	MeTxynoL2: "framer-v-1hhrxj3",
	O8p5JbvBg: "framer-v-389x50",
	tlHcUv3w4: "framer-v-l4n959",
	vA5FUeUvu: "framer-v-1k9eonw",
	ZMh3rRVPs: "framer-v-1cvy2t",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	delay: 0,
	duration: 0.6,
	ease: [0.12, 0.23, 0.5, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition12,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: -40,
};
var transition2 = {
	damping: 40,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var transition3 = {
	delay: 0,
	duration: 0.4,
	ease: [0.12, 0.23, 0.5, 1],
	type: "tween",
};
var transition4 = {
	delay: 0,
	duration: 0.3,
	ease: [0.12, 0.23, 0.5, 1],
	type: "tween",
};
var transition5 = {
	delay: 0.1,
	duration: 0.4,
	ease: [0.12, 0.23, 0.5, 1],
	type: "tween",
};
var animation2 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition5,
	x: 0,
	y: 0,
};
var animation3 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition6 = {
	delay: 0.2,
	duration: 0.4,
	ease: [0.12, 0.23, 0.5, 1],
	type: "tween",
};
var animation4 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition6,
	x: 0,
	y: 0,
};
var transition7 = {
	delay: 0.3,
	duration: 0.4,
	ease: [0.12, 0.23, 0.5, 1],
	type: "tween",
};
var animation5 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition7,
	x: 0,
	y: 0,
};
var transition8 = {
	delay: 0.4,
	duration: 0.4,
	ease: [0.12, 0.23, 0.5, 1],
	type: "tween",
};
var animation6 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition8,
	x: 0,
	y: 0,
};
var transition9 = {
	delay: 0.5,
	duration: 0.4,
	ease: [0.12, 0.23, 0.5, 1],
	type: "tween",
};
var animation7 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition9,
	x: 0,
	y: 0,
};
var transition10 = {
	delay: 0.5,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation8 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition10,
	x: 0,
	y: 0,
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	"Desktop Scroll": "gfzXc5QXH",
	"Phone Close": "ZMh3rRVPs",
	"Phone Open": "tlHcUv3w4",
	"Phone Scroll": "KMUe7lBtZ",
	"Tablet Close": "MeTxynoL2",
	"Tablet Open": "avm8OLc_A",
	"Tablet Scroll": "vA5FUeUvu",
	Desktop: "O8p5JbvBg",
};
var getProps2 = ({ height, id, link, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "O8p5JbvBg",
		ycH1W8s7_: link ?? props.ycH1W8s7_,
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const { style, className, layoutId, variant, ycH1W8s7_, ...restProps } =
		getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "O8p5JbvBg",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback2(baseVariant);
	const onTapb1j3bq = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("MeTxynoL2");
	});
	const onTapmfyew3 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("ZMh3rRVPs");
	});
	const onTap12y5d4a = activeVariantCallback(async (...args) => {
		setVariant("MeTxynoL2");
	});
	const onTap1nknyp7 = activeVariantCallback(async (...args) => {
		setVariant("ZMh3rRVPs");
	});
	const kfdTaiDBR15ek400 = activeVariantCallback(async (...args) => {
		setVariant("avm8OLc_A");
	});
	const kfdTaiDBR12y5d4a = activeVariantCallback(async (...args) => {
		setVariant("MeTxynoL2");
	});
	const kfdTaiDBR1jm1viq = activeVariantCallback(async (...args) => {
		setVariant("tlHcUv3w4");
	});
	const kfdTaiDBR1nknyp7 = activeVariantCallback(async (...args) => {
		setVariant("ZMh3rRVPs");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (
			[
				"MeTxynoL2",
				"avm8OLc_A",
				"ZMh3rRVPs",
				"tlHcUv3w4",
				"vA5FUeUvu",
				"KMUe7lBtZ",
			].includes(baseVariant)
		)
			return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (["ZMh3rRVPs", "tlHcUv3w4"].includes(baseVariant)) return false;
		return true;
	};
	const isDisplayed2 = () => {
		if (["vA5FUeUvu", "KMUe7lBtZ"].includes(baseVariant)) return false;
		return true;
	};
	const isDisplayed3 = () => {
		if (
			["MeTxynoL2", "ZMh3rRVPs", "vA5FUeUvu", "KMUe7lBtZ"].includes(baseVariant)
		)
			return false;
		return true;
	};
	const isDisplayed4 = () => {
		if (baseVariant === "gfzXc5QXH") return false;
		return true;
	};
	const router = useRouter();
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2
					value={transition2}
					{...addPropertyOverrides2(
						{
							avm8OLc_A: {
								value: transition4,
							},
							MeTxynoL2: {
								value: transition3,
							},
							tlHcUv3w4: {
								value: transition4,
							},
							ZMh3rRVPs: {
								value: transition3,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<MotionNavWithFXWithOptimizedAppearEffect
						{...restProps}
						{...gestureHandlers}
						__framer__presenceAnimate={animation}
						__framer__presenceInitial={animation1}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						className={cx2(
							scopingClassNames,
							"framer-389x50",
							className,
							classNames,
						)}
						data-framer-appear-id={"389x50"}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"O8p5JbvBg"}
						optimized={true}
						ref={refBinding}
						style={{
							backdropFilter: "none",
							backgroundColor:
								"var(--token-14605fce-5bc9-43c8-a91c-723bc4169ca1, rgba(0, 0, 0, 0))",
							borderBottomLeftRadius: 0,
							borderBottomRightRadius: 0,
							WebkitBackdropFilter: "none",
							...style,
						}}
						variants={{
							avm8OLc_A: {
								backdropFilter: "blur(5px)",
								backgroundColor:
									"var(--token-12cbfa94-9c5f-41d3-a67b-614d50367bfe, rgb(17, 17, 20))",
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								WebkitBackdropFilter: "blur(5px)",
							},
							gfzXc5QXH: {
								backdropFilter: "none",
								borderBottomLeftRadius: 0,
								borderBottomRightRadius: 0,
								WebkitBackdropFilter: "none",
							},
							KMUe7lBtZ: {
								backdropFilter: "none",
								borderBottomLeftRadius: 0,
								borderBottomRightRadius: 0,
								WebkitBackdropFilter: "none",
							},
							tlHcUv3w4: {
								backdropFilter: "none",
								backgroundColor:
									"var(--token-12cbfa94-9c5f-41d3-a67b-614d50367bfe, rgb(17, 17, 20))",
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								WebkitBackdropFilter: "none",
							},
							vA5FUeUvu: {
								backdropFilter: "none",
								borderBottomLeftRadius: 0,
								borderBottomRightRadius: 0,
								WebkitBackdropFilter: "none",
							},
							ZMh3rRVPs: {
								backdropFilter: "none",
								borderBottomLeftRadius: 0,
								borderBottomRightRadius: 0,
								WebkitBackdropFilter: "none",
							},
						}}
						{...addPropertyOverrides2(
							{
								avm8OLc_A: {
									"data-framer-name": "Tablet Open",
									"data-highlight": true,
									onTap: onTapb1j3bq,
								},
								gfzXc5QXH: {
									"data-framer-name": "Desktop Scroll",
								},
								KMUe7lBtZ: {
									"data-framer-name": "Phone Scroll",
								},
								MeTxynoL2: {
									"data-framer-name": "Tablet Close",
								},
								tlHcUv3w4: {
									"data-framer-name": "Phone Open",
									"data-highlight": true,
									onTap: onTapmfyew3,
								},
								vA5FUeUvu: {
									"data-framer-name": "Tablet Scroll",
								},
								ZMh3rRVPs: {
									"data-framer-name": "Phone Close",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-fzdypl"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"JvM6mMlFf"}
							style={{
								backdropFilter: "none",
								backgroundColor: "rgba(0, 0, 0, 0)",
								borderBottomLeftRadius: 0,
								borderBottomRightRadius: 0,
								borderTopLeftRadius: 0,
								borderTopRightRadius: 0,
								WebkitBackdropFilter: "none",
							}}
							variants={{
								gfzXc5QXH: {
									backdropFilter: "blur(10px)",
									backgroundColor:
										"var(--token-14605fce-5bc9-43c8-a91c-723bc4169ca1, rgba(0, 0, 0, 0))",
									borderBottomLeftRadius: 33,
									borderBottomRightRadius: 33,
									borderTopLeftRadius: 33,
									borderTopRightRadius: 33,
									WebkitBackdropFilter: "blur(10px)",
								},
								KMUe7lBtZ: {
									backdropFilter: "none",
									backgroundColor: "rgba(0, 0, 0, 0)",
									borderBottomLeftRadius: 0,
									borderBottomRightRadius: 0,
									borderTopLeftRadius: 0,
									borderTopRightRadius: 0,
									WebkitBackdropFilter: "none",
								},
								vA5FUeUvu: {
									backdropFilter: "none",
									backgroundColor: "rgba(0, 0, 0, 0)",
									borderBottomLeftRadius: 0,
									borderBottomRightRadius: 0,
									borderTopLeftRadius: 0,
									borderTopRightRadius: 0,
									WebkitBackdropFilter: "none",
								},
							}}
						>
							<motion2.div
								className={"framer-b7ke7f"}
								data-framer-name={"Logo"}
								layoutDependency={layoutDependency}
								layoutId={"PDAF7fF4u"}
								style={{
									backdropFilter: "none",
									backgroundColor: "rgba(0, 0, 0, 0)",
									borderBottomLeftRadius: 0,
									borderBottomRightRadius: 0,
									borderTopLeftRadius: 0,
									borderTopRightRadius: 0,
									WebkitBackdropFilter: "none",
								}}
								variants={{
									KMUe7lBtZ: {
										backdropFilter: "blur(10px)",
										backgroundColor:
											"var(--token-14605fce-5bc9-43c8-a91c-723bc4169ca1, rgba(0, 0, 0, 0))",
										borderBottomLeftRadius: 27,
										borderBottomRightRadius: 27,
										borderTopLeftRadius: 27,
										borderTopRightRadius: 27,
										WebkitBackdropFilter: "blur(10px)",
									},
									vA5FUeUvu: {
										backdropFilter: "blur(10px)",
										backgroundColor:
											"var(--token-14605fce-5bc9-43c8-a91c-723bc4169ca1, rgba(0, 0, 0, 0))",
										borderBottomLeftRadius: 29,
										borderBottomRightRadius: 29,
										borderTopLeftRadius: 29,
										borderTopRightRadius: 29,
										WebkitBackdropFilter: "blur(10px)",
									},
								}}
							>
								<Link
									href={{
										webPageId: "ngHctEoI7",
									}}
									motionChild={true}
									nodeId={"b20_m5o3p"}
									scopeId={"j8Sly2SM6"}
								>
									<Image
										aria-label={"Company Logo"}
										as={"a"}
										background={{
											alt: "",
											fit: "fit",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													(16 +
														((componentViewport?.height || 200) - 32 - 50) /
															2) +
													5 +
													0,
											),
											pixelHeight: 149,
											pixelWidth: 520,
											positionX: "center",
											positionY: "center",
											sizes: "152px",
											src: "https://framerusercontent.com/images/tJ1jqpEOBL9Nna5facx9Yh1rSA.svg?width=520&height=149",
											srcSet:
												"https://framerusercontent.com/images/tJ1jqpEOBL9Nna5facx9Yh1rSA.svg?scale-down-to=512&width=520&height=149 512w,https://framerusercontent.com/images/tJ1jqpEOBL9Nna5facx9Yh1rSA.svg?width=520&height=149 520w",
										}}
										className={"framer-f5khec framer-soh4vb"}
										data-framer-name={"Logo"}
										layoutDependency={layoutDependency}
										layoutId={"b20_m5o3p"}
										style={{
											filter: "none",
											WebkitFilter: "none",
										}}
										variants={{
											gfzXc5QXH: {
												filter: "invert(0)",
												WebkitFilter: "invert(0)",
											},
											KMUe7lBtZ: {
												filter: "invert(0)",
												WebkitFilter: "invert(0)",
											},
											vA5FUeUvu: {
												filter: "invert(0)",
												WebkitFilter: "invert(0)",
											},
										}}
										{...addPropertyOverrides2(
											{
												avm8OLc_A: {
													"data-highlight": true,
													background: {
														alt: "",
														fit: "fit",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																16 +
																(((componentViewport?.height || 200) -
																	32 -
																	498) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																80,
														),
														pixelHeight: 149,
														pixelWidth: 520,
														positionX: "center",
														positionY: "center",
														sizes: "152px",
														src: "https://framerusercontent.com/images/tJ1jqpEOBL9Nna5facx9Yh1rSA.svg?width=520&height=149",
														srcSet:
															"https://framerusercontent.com/images/tJ1jqpEOBL9Nna5facx9Yh1rSA.svg?scale-down-to=512&width=520&height=149 512w,https://framerusercontent.com/images/tJ1jqpEOBL9Nna5facx9Yh1rSA.svg?width=520&height=149 520w",
													},
													onTap: onTap12y5d4a,
												},
												gfzXc5QXH: {
													background: {
														alt: "",
														fit: "fit",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																(16 +
																	((componentViewport?.height || 200) -
																		32 -
																		58) /
																		2) +
																9 +
																0,
														),
														pixelHeight: 149,
														pixelWidth: 520,
														positionX: "center",
														positionY: "center",
														sizes: "152px",
														src: "https://framerusercontent.com/images/tJ1jqpEOBL9Nna5facx9Yh1rSA.svg?width=520&height=149",
														srcSet:
															"https://framerusercontent.com/images/tJ1jqpEOBL9Nna5facx9Yh1rSA.svg?scale-down-to=512&width=520&height=149 512w,https://framerusercontent.com/images/tJ1jqpEOBL9Nna5facx9Yh1rSA.svg?width=520&height=149 520w",
													},
												},
												KMUe7lBtZ: {
													background: {
														alt: "",
														fit: "fit",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																16 +
																(((componentViewport?.height || 200) -
																	32 -
																	54) /
																	2 +
																	0 +
																	0) +
																0 +
																10,
														),
														pixelHeight: 149,
														pixelWidth: 520,
														positionX: "center",
														positionY: "center",
														sizes: "125px",
														src: "https://framerusercontent.com/images/tJ1jqpEOBL9Nna5facx9Yh1rSA.svg?width=520&height=149",
														srcSet:
															"https://framerusercontent.com/images/tJ1jqpEOBL9Nna5facx9Yh1rSA.svg?scale-down-to=512&width=520&height=149 512w,https://framerusercontent.com/images/tJ1jqpEOBL9Nna5facx9Yh1rSA.svg?width=520&height=149 520w",
													},
												},
												MeTxynoL2: {
													background: {
														alt: "",
														fit: "fit",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																16 +
																(((componentViewport?.height || 200) -
																	32 -
																	200) /
																	2 +
																	0 +
																	0) +
																0 +
																80,
														),
														pixelHeight: 149,
														pixelWidth: 520,
														positionX: "center",
														positionY: "center",
														sizes: "152px",
														src: "https://framerusercontent.com/images/tJ1jqpEOBL9Nna5facx9Yh1rSA.svg?width=520&height=149",
														srcSet:
															"https://framerusercontent.com/images/tJ1jqpEOBL9Nna5facx9Yh1rSA.svg?scale-down-to=512&width=520&height=149 512w,https://framerusercontent.com/images/tJ1jqpEOBL9Nna5facx9Yh1rSA.svg?width=520&height=149 520w",
													},
												},
												tlHcUv3w4: {
													"data-highlight": true,
													background: {
														alt: "",
														fit: "fit",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																16 +
																(((componentViewport?.height || 200) -
																	32 -
																	498) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																81,
														),
														pixelHeight: 149,
														pixelWidth: 520,
														positionX: "center",
														positionY: "center",
														sizes: "140.5px",
														src: "https://framerusercontent.com/images/tJ1jqpEOBL9Nna5facx9Yh1rSA.svg?width=520&height=149",
														srcSet:
															"https://framerusercontent.com/images/tJ1jqpEOBL9Nna5facx9Yh1rSA.svg?scale-down-to=512&width=520&height=149 512w,https://framerusercontent.com/images/tJ1jqpEOBL9Nna5facx9Yh1rSA.svg?width=520&height=149 520w",
													},
													onTap: onTap1nknyp7,
												},
												vA5FUeUvu: {
													background: {
														alt: "",
														fit: "fit",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																16 +
																(((componentViewport?.height || 200) -
																	32 -
																	58) /
																	2 +
																	0 +
																	0) +
																0 +
																9,
														),
														pixelHeight: 149,
														pixelWidth: 520,
														positionX: "center",
														positionY: "center",
														sizes: "152px",
														src: "https://framerusercontent.com/images/tJ1jqpEOBL9Nna5facx9Yh1rSA.svg?width=520&height=149",
														srcSet:
															"https://framerusercontent.com/images/tJ1jqpEOBL9Nna5facx9Yh1rSA.svg?scale-down-to=512&width=520&height=149 512w,https://framerusercontent.com/images/tJ1jqpEOBL9Nna5facx9Yh1rSA.svg?width=520&height=149 520w",
													},
												},
												ZMh3rRVPs: {
													background: {
														alt: "",
														fit: "fit",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																16 +
																(((componentViewport?.height || 200) -
																	32 -
																	200) /
																	2 +
																	0 +
																	0) +
																0 +
																81,
														),
														pixelHeight: 149,
														pixelWidth: 520,
														positionX: "center",
														positionY: "center",
														sizes: "140.5px",
														src: "https://framerusercontent.com/images/tJ1jqpEOBL9Nna5facx9Yh1rSA.svg?width=520&height=149",
														srcSet:
															"https://framerusercontent.com/images/tJ1jqpEOBL9Nna5facx9Yh1rSA.svg?scale-down-to=512&width=520&height=149 512w,https://framerusercontent.com/images/tJ1jqpEOBL9Nna5facx9Yh1rSA.svg?width=520&height=149 520w",
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</Link>
								{isDisplayed() && (
									<motion2.div
										className={"framer-bxnwrn"}
										data-framer-name={"Other"}
										layoutDependency={layoutDependency}
										layoutId={"uPrdkpNUA"}
									>
										{isDisplayed1() && (
											<ComponentViewportProvider
												height={50}
												{...addPropertyOverrides2(
													{
														avm8OLc_A: {
															y:
																(componentViewport?.y || 0) +
																16 +
																(((componentViewport?.height || 200) -
																	32 -
																	498) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																75,
														},
														KMUe7lBtZ: {
															y:
																(componentViewport?.y || 0) +
																16 +
																(((componentViewport?.height || 200) -
																	32 -
																	54) /
																	2 +
																	0 +
																	0) +
																0 +
																2 +
																0,
														},
														MeTxynoL2: {
															y:
																(componentViewport?.y || 0) +
																16 +
																(((componentViewport?.height || 200) -
																	32 -
																	200) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																75,
														},
														vA5FUeUvu: {
															y:
																(componentViewport?.y || 0) +
																16 +
																(((componentViewport?.height || 200) -
																	32 -
																	58) /
																	2 +
																	0 +
																	0) +
																0 +
																4 +
																0,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-129tb6z-container"}
													layoutDependency={layoutDependency}
													layoutId={"eeMofVizs-container"}
													nodeId={"eeMofVizs"}
													rendersWithMotion={true}
													scopeId={"j8Sly2SM6"}
												>
													{_jsx2(stdin_default2, {
														enDzQkQtN: true,
														height: "100%",
														id: "eeMofVizs",
														layoutId: "eeMofVizs",
														si0GkhZ8V: "Get Ticket",
														U9RyfAHsf: ycH1W8s7_,
														variant: "chB_amfp7",
														width: "100%",
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
										{isDisplayed2() && (
											<ComponentViewportProvider
												height={200}
												{...addPropertyOverrides2(
													{
														avm8OLc_A: {
															y:
																(componentViewport?.y || 0) +
																16 +
																(((componentViewport?.height || 200) -
																	32 -
																	498) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																0,
														},
														MeTxynoL2: {
															y:
																(componentViewport?.y || 0) +
																16 +
																(((componentViewport?.height || 200) -
																	32 -
																	200) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0,
														},
														tlHcUv3w4: {
															y:
																(componentViewport?.y || 0) +
																16 +
																(((componentViewport?.height || 200) -
																	32 -
																	498) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																0,
														},
														ZMh3rRVPs: {
															y:
																(componentViewport?.y || 0) +
																16 +
																(((componentViewport?.height || 200) -
																	32 -
																	200) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-1sw86a4-container"}
													layoutDependency={layoutDependency}
													layoutId={"q1xG5YyL6-container"}
													nodeId={"q1xG5YyL6"}
													rendersWithMotion={true}
													scopeId={"j8Sly2SM6"}
												>
													{_jsx2(stdin_default3, {
														height: "100%",
														id: "q1xG5YyL6",
														layoutId: "q1xG5YyL6",
														variant: "X165QcoAj",
														width: "100%",
														...addPropertyOverrides2(
															{
																avm8OLc_A: {
																	kfdTaiDBR: kfdTaiDBR12y5d4a,
																	variant: "FRgnkpAWf",
																},
																MeTxynoL2: {
																	kfdTaiDBR: kfdTaiDBR15ek400,
																},
																tlHcUv3w4: {
																	kfdTaiDBR: kfdTaiDBR1nknyp7,
																	variant: "FRgnkpAWf",
																},
																ZMh3rRVPs: {
																	kfdTaiDBR: kfdTaiDBR1jm1viq,
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</motion2.div>
								)}
							</motion2.div>
							{isDisplayed3() && (
								<motion2.div
									className={"framer-18kiu0w"}
									data-framer-name={"Content"}
									layoutDependency={layoutDependency}
									layoutId={"wDTrnLsic"}
								>
									{isDisplayed4() && (
										<motion2.nav
											className={"framer-1s42b8a"}
											data-framer-name={"Links"}
											layoutDependency={layoutDependency}
											layoutId={"lvEyQQvr3"}
										>
											<ResolveLinks
												links={[
													{
														href: {
															webPageId: "H5KkvzB6J",
														},
														implicitPathVariables: void 0,
													},
													{
														href: {
															webPageId: "H5KkvzB6J",
														},
														implicitPathVariables: void 0,
													},
													{
														href: {
															webPageId: "H5KkvzB6J",
														},
														implicitPathVariables: void 0,
													},
												]}
											>
												{(resolvedLinks) => (
													<ComponentViewportProvider
														height={40}
														y={
															(componentViewport?.y || 0) +
															(16 +
																((componentViewport?.height || 200) - 32 - 50) /
																	2) +
															0 +
															5 +
															0
														}
														{...addPropertyOverrides2(
															{
																avm8OLc_A: {
																	y:
																		(componentViewport?.y || 0) +
																		16 +
																		(((componentViewport?.height || 200) -
																			32 -
																			498) /
																			2 +
																			0 +
																			0) +
																		0 +
																		224 +
																		0 +
																		0 +
																		0 +
																		0,
																},
																tlHcUv3w4: {
																	y:
																		(componentViewport?.y || 0) +
																		16 +
																		(((componentViewport?.height || 200) -
																			32 -
																			498) /
																			2 +
																			0 +
																			0) +
																		0 +
																		224 +
																		0 +
																		0 +
																		0 +
																		0,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<SmartComponentScopedContainerWithFXWithOptimizedAppearEffect
															className={"framer-fwhbux-container"}
															data-framer-appear-id={"fwhbux"}
															layoutDependency={layoutDependency}
															layoutId={"rLtqS9eOW-container"}
															nodeId={"rLtqS9eOW"}
															rendersWithMotion={true}
															scopeId={"j8Sly2SM6"}
															{...addPropertyOverrides2(
																{
																	avm8OLc_A: {
																		__perspectiveFX: false,
																		__smartComponentFX: true,
																		__targetOpacity: 1,
																		animate: animation2,
																		initial: animation3,
																		optimized: true,
																	},
																	tlHcUv3w4: {
																		__perspectiveFX: false,
																		__smartComponentFX: true,
																		__targetOpacity: 1,
																		animate: animation2,
																		initial: animation3,
																		optimized: true,
																	},
																},
																baseVariant,
																gestureVariant,
															)}
														>
															{_jsx2(stdin_default, {
																ac4JHN6Mf: resolvedLinks[0],
																FXv52DSLw: false,
																height: "100%",
																id: "rLtqS9eOW",
																layoutId: "rLtqS9eOW",
																variant: "NqmrBcKU0",
																width: "100%",
																Xg1a7VaWe: "Speaker",
																...addPropertyOverrides2(
																	{
																		avm8OLc_A: {
																			ac4JHN6Mf: resolvedLinks[1],
																		},
																		tlHcUv3w4: {
																			ac4JHN6Mf: resolvedLinks[2],
																			variant: "HK7rTO971",
																		},
																	},
																	baseVariant,
																	gestureVariant,
																),
															})}
														</SmartComponentScopedContainerWithFXWithOptimizedAppearEffect>
													</ComponentViewportProvider>
												)}
											</ResolveLinks>
											<ResolveLinks
												links={[
													{
														href: {
															webPageId: "Aw1bp1qBS",
														},
														implicitPathVariables: void 0,
													},
													{
														href: {
															webPageId: "Aw1bp1qBS",
														},
														implicitPathVariables: void 0,
													},
													{
														href: {
															webPageId: "Aw1bp1qBS",
														},
														implicitPathVariables: void 0,
													},
												]}
											>
												{(resolvedLinks1) => (
													<ComponentViewportProvider
														height={40}
														y={
															(componentViewport?.y || 0) +
															(16 +
																((componentViewport?.height || 200) - 32 - 50) /
																	2) +
															0 +
															5 +
															0
														}
														{...addPropertyOverrides2(
															{
																avm8OLc_A: {
																	y:
																		(componentViewport?.y || 0) +
																		16 +
																		(((componentViewport?.height || 200) -
																			32 -
																			498) /
																			2 +
																			0 +
																			0) +
																		0 +
																		224 +
																		0 +
																		0 +
																		0 +
																		56,
																},
																tlHcUv3w4: {
																	y:
																		(componentViewport?.y || 0) +
																		16 +
																		(((componentViewport?.height || 200) -
																			32 -
																			498) /
																			2 +
																			0 +
																			0) +
																		0 +
																		224 +
																		0 +
																		0 +
																		0 +
																		56,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<SmartComponentScopedContainerWithFXWithOptimizedAppearEffect
															className={"framer-10o80ne-container"}
															data-framer-appear-id={"10o80ne"}
															layoutDependency={layoutDependency}
															layoutId={"ogW54qU3L-container"}
															nodeId={"ogW54qU3L"}
															rendersWithMotion={true}
															scopeId={"j8Sly2SM6"}
															{...addPropertyOverrides2(
																{
																	avm8OLc_A: {
																		__perspectiveFX: false,
																		__smartComponentFX: true,
																		__targetOpacity: 1,
																		animate: animation4,
																		initial: animation3,
																		optimized: true,
																	},
																	tlHcUv3w4: {
																		__perspectiveFX: false,
																		__smartComponentFX: true,
																		__targetOpacity: 1,
																		animate: animation4,
																		initial: animation3,
																		optimized: true,
																	},
																},
																baseVariant,
																gestureVariant,
															)}
														>
															{_jsx2(stdin_default, {
																ac4JHN6Mf: resolvedLinks1[0],
																FXv52DSLw: false,
																height: "100%",
																id: "ogW54qU3L",
																layoutId: "ogW54qU3L",
																variant: "NqmrBcKU0",
																width: "100%",
																Xg1a7VaWe: "Agenda",
																...addPropertyOverrides2(
																	{
																		avm8OLc_A: {
																			ac4JHN6Mf: resolvedLinks1[1],
																		},
																		tlHcUv3w4: {
																			ac4JHN6Mf: resolvedLinks1[2],
																			variant: "HK7rTO971",
																		},
																	},
																	baseVariant,
																	gestureVariant,
																),
															})}
														</SmartComponentScopedContainerWithFXWithOptimizedAppearEffect>
													</ComponentViewportProvider>
												)}
											</ResolveLinks>
											<ResolveLinks
												links={[
													{
														href: {
															webPageId: "vrrKLizBH",
														},
														implicitPathVariables: void 0,
													},
													{
														href: {
															webPageId: "vrrKLizBH",
														},
														implicitPathVariables: void 0,
													},
													{
														href: {
															webPageId: "vrrKLizBH",
														},
														implicitPathVariables: void 0,
													},
												]}
											>
												{(resolvedLinks2) => (
													<ComponentViewportProvider
														height={40}
														y={
															(componentViewport?.y || 0) +
															(16 +
																((componentViewport?.height || 200) - 32 - 50) /
																	2) +
															0 +
															5 +
															0
														}
														{...addPropertyOverrides2(
															{
																avm8OLc_A: {
																	y:
																		(componentViewport?.y || 0) +
																		16 +
																		(((componentViewport?.height || 200) -
																			32 -
																			498) /
																			2 +
																			0 +
																			0) +
																		0 +
																		224 +
																		0 +
																		0 +
																		0 +
																		112,
																},
																tlHcUv3w4: {
																	y:
																		(componentViewport?.y || 0) +
																		16 +
																		(((componentViewport?.height || 200) -
																			32 -
																			498) /
																			2 +
																			0 +
																			0) +
																		0 +
																		224 +
																		0 +
																		0 +
																		0 +
																		112,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<SmartComponentScopedContainerWithFXWithOptimizedAppearEffect
															className={"framer-1ycfse4-container"}
															data-framer-appear-id={"1ycfse4"}
															layoutDependency={layoutDependency}
															layoutId={"aM_nXp9p5-container"}
															nodeId={"aM_nXp9p5"}
															rendersWithMotion={true}
															scopeId={"j8Sly2SM6"}
															{...addPropertyOverrides2(
																{
																	avm8OLc_A: {
																		__perspectiveFX: false,
																		__smartComponentFX: true,
																		__targetOpacity: 1,
																		animate: animation5,
																		initial: animation3,
																		optimized: true,
																	},
																	tlHcUv3w4: {
																		__perspectiveFX: false,
																		__smartComponentFX: true,
																		__targetOpacity: 1,
																		animate: animation5,
																		initial: animation3,
																		optimized: true,
																	},
																},
																baseVariant,
																gestureVariant,
															)}
														>
															{_jsx2(stdin_default, {
																ac4JHN6Mf: resolvedLinks2[0],
																FXv52DSLw: false,
																height: "100%",
																id: "aM_nXp9p5",
																layoutId: "aM_nXp9p5",
																variant: "NqmrBcKU0",
																width: "100%",
																Xg1a7VaWe: "Venue",
																...addPropertyOverrides2(
																	{
																		avm8OLc_A: {
																			ac4JHN6Mf: resolvedLinks2[1],
																		},
																		tlHcUv3w4: {
																			ac4JHN6Mf: resolvedLinks2[2],
																			variant: "HK7rTO971",
																		},
																	},
																	baseVariant,
																	gestureVariant,
																),
															})}
														</SmartComponentScopedContainerWithFXWithOptimizedAppearEffect>
													</ComponentViewportProvider>
												)}
											</ResolveLinks>
											<ResolveLinks
												links={[
													{
														href: {
															webPageId: "tgsKZLLek",
														},
														implicitPathVariables: void 0,
													},
													{
														href: {
															webPageId: "tgsKZLLek",
														},
														implicitPathVariables: void 0,
													},
													{
														href: {
															webPageId: "tgsKZLLek",
														},
														implicitPathVariables: void 0,
													},
												]}
											>
												{(resolvedLinks3) => (
													<ComponentViewportProvider
														height={40}
														y={
															(componentViewport?.y || 0) +
															(16 +
																((componentViewport?.height || 200) - 32 - 50) /
																	2) +
															0 +
															5 +
															0
														}
														{...addPropertyOverrides2(
															{
																avm8OLc_A: {
																	y:
																		(componentViewport?.y || 0) +
																		16 +
																		(((componentViewport?.height || 200) -
																			32 -
																			498) /
																			2 +
																			0 +
																			0) +
																		0 +
																		224 +
																		0 +
																		0 +
																		0 +
																		168,
																},
																tlHcUv3w4: {
																	y:
																		(componentViewport?.y || 0) +
																		16 +
																		(((componentViewport?.height || 200) -
																			32 -
																			498) /
																			2 +
																			0 +
																			0) +
																		0 +
																		224 +
																		0 +
																		0 +
																		0 +
																		168,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<SmartComponentScopedContainerWithFXWithOptimizedAppearEffect
															className={"framer-1dvu7jj-container"}
															data-framer-appear-id={"1dvu7jj"}
															layoutDependency={layoutDependency}
															layoutId={"Qj7DUxEy5-container"}
															nodeId={"Qj7DUxEy5"}
															rendersWithMotion={true}
															scopeId={"j8Sly2SM6"}
															{...addPropertyOverrides2(
																{
																	avm8OLc_A: {
																		__perspectiveFX: false,
																		__smartComponentFX: true,
																		__targetOpacity: 1,
																		animate: animation6,
																		initial: animation3,
																		optimized: true,
																	},
																	tlHcUv3w4: {
																		__perspectiveFX: false,
																		__smartComponentFX: true,
																		__targetOpacity: 1,
																		animate: animation6,
																		initial: animation3,
																		optimized: true,
																	},
																},
																baseVariant,
																gestureVariant,
															)}
														>
															{_jsx2(stdin_default, {
																ac4JHN6Mf: resolvedLinks3[0],
																FXv52DSLw: false,
																height: "100%",
																id: "Qj7DUxEy5",
																layoutId: "Qj7DUxEy5",
																variant: "NqmrBcKU0",
																width: "100%",
																Xg1a7VaWe: "Contact",
																...addPropertyOverrides2(
																	{
																		avm8OLc_A: {
																			ac4JHN6Mf: resolvedLinks3[1],
																		},
																		tlHcUv3w4: {
																			ac4JHN6Mf: resolvedLinks3[2],
																			variant: "HK7rTO971",
																		},
																	},
																	baseVariant,
																	gestureVariant,
																),
															})}
														</SmartComponentScopedContainerWithFXWithOptimizedAppearEffect>
													</ComponentViewportProvider>
												)}
											</ResolveLinks>
										</motion2.nav>
									)}
									<ComponentViewportProvider
										height={50}
										y={
											(componentViewport?.y || 0) +
											(16 +
												((componentViewport?.height || 200) - 32 - 50) / 2) +
											0 +
											0
										}
										{...addPropertyOverrides2(
											{
												avm8OLc_A: {
													y:
														(componentViewport?.y || 0) +
														16 +
														(((componentViewport?.height || 200) - 32 - 498) /
															2 +
															0 +
															0) +
														0 +
														224 +
														0 +
														224,
												},
												gfzXc5QXH: {
													y:
														(componentViewport?.y || 0) +
														(16 +
															((componentViewport?.height || 200) - 32 - 58) /
																2) +
														4 +
														0,
												},
												tlHcUv3w4: {
													y:
														(componentViewport?.y || 0) +
														16 +
														(((componentViewport?.height || 200) - 32 - 498) /
															2 +
															0 +
															0) +
														0 +
														224 +
														0 +
														224,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainerWithFXWithOptimizedAppearEffect
											className={"framer-yk7xmc-container"}
											data-framer-appear-id={"yk7xmc"}
											layoutDependency={layoutDependency}
											layoutId={"XKm_f8E9v-container"}
											nodeId={"XKm_f8E9v"}
											rendersWithMotion={true}
											scopeId={"j8Sly2SM6"}
											{...addPropertyOverrides2(
												{
													avm8OLc_A: {
														__perspectiveFX: false,
														__smartComponentFX: true,
														__targetOpacity: 1,
														animate: animation7,
														initial: animation3,
														optimized: true,
													},
													tlHcUv3w4: {
														__perspectiveFX: false,
														__smartComponentFX: true,
														__targetOpacity: 1,
														animate: animation8,
														initial: animation3,
														optimized: true,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											{_jsx2(stdin_default2, {
												enDzQkQtN: true,
												height: "100%",
												id: "XKm_f8E9v",
												layoutId: "XKm_f8E9v",
												si0GkhZ8V: "Get Ticket",
												U9RyfAHsf: ycH1W8s7_,
												variant: "chB_amfp7",
												width: "100%",
												...addPropertyOverrides2(
													{
														tlHcUv3w4: {
															variant: "E4GQrfmDw",
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainerWithFXWithOptimizedAppearEffect>
									</ComponentViewportProvider>
								</motion2.div>
							)}
						</motion2.div>
					</MotionNavWithFXWithOptimizedAppearEffect>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Luar2.framer-soh4vb, .framer-Luar2 .framer-soh4vb { display: block; }",
	".framer-Luar2.framer-389x50 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: center; overflow: hidden; padding: 16px 40px 16px 40px; position: relative; width: 1200px; }",
	".framer-Luar2 .framer-fzdypl { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-Luar2 .framer-b7ke7f, .framer-Luar2 .framer-bxnwrn { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-Luar2 .framer-f5khec { aspect-ratio: 3.8 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 40px); overflow: hidden; position: relative; text-decoration: none; width: 152px; }",
	".framer-Luar2 .framer-129tb6z-container, .framer-Luar2 .framer-1sw86a4-container, .framer-Luar2 .framer-fwhbux-container, .framer-Luar2 .framer-10o80ne-container, .framer-Luar2 .framer-1ycfse4-container, .framer-Luar2 .framer-1dvu7jj-container, .framer-Luar2 .framer-yk7xmc-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-Luar2 .framer-18kiu0w { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-end; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-Luar2 .framer-1s42b8a { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-Luar2.framer-v-1hhrxj3.framer-389x50, .framer-Luar2.framer-v-1k9eonw.framer-389x50 { flex-direction: column; width: 810px; }",
	".framer-Luar2.framer-v-1hhrxj3 .framer-fzdypl, .framer-Luar2.framer-v-1cvy2t .framer-fzdypl, .framer-Luar2.framer-v-1k9eonw .framer-fzdypl, .framer-Luar2.framer-v-wz6pu4 .framer-fzdypl { flex: none; width: 100%; }",
	".framer-Luar2.framer-v-1hhrxj3 .framer-b7ke7f, .framer-Luar2.framer-v-1cvy2t .framer-b7ke7f { flex: 1 0 0px; gap: unset; justify-content: space-between; width: 1px; }",
	".framer-Luar2.framer-v-15y03z2.framer-389x50 { cursor: pointer; flex-direction: column; width: 810px; will-change: var(--framer-will-change-override, transform); }",
	".framer-Luar2.framer-v-15y03z2 .framer-fzdypl, .framer-Luar2.framer-v-l4n959 .framer-fzdypl { flex: none; flex-direction: column; gap: 24px; width: 100%; }",
	".framer-Luar2.framer-v-15y03z2 .framer-b7ke7f, .framer-Luar2.framer-v-l4n959 .framer-b7ke7f { gap: unset; justify-content: space-between; width: 100%; }",
	".framer-Luar2.framer-v-15y03z2 .framer-f5khec { cursor: pointer; }",
	".framer-Luar2.framer-v-15y03z2 .framer-18kiu0w { flex: none; flex-direction: column; gap: 16px; width: 100%; }",
	".framer-Luar2.framer-v-15y03z2 .framer-1s42b8a, .framer-Luar2.framer-v-l4n959 .framer-1s42b8a { flex-direction: column; gap: 16px; }",
	".framer-Luar2.framer-v-1cvy2t.framer-389x50, .framer-Luar2.framer-v-wz6pu4.framer-389x50 { flex-direction: column; gap: 20px; padding: 16px 20px 16px 20px; width: 390px; }",
	".framer-Luar2.framer-v-1cvy2t .framer-f5khec { height: var(--framer-aspect-ratio-supported, 38px); width: 141px; }",
	".framer-Luar2.framer-v-l4n959.framer-389x50 { cursor: pointer; flex-direction: column; gap: 16px; padding: 16px 20px 16px 20px; width: 390px; will-change: var(--framer-will-change-override, transform); }",
	".framer-Luar2.framer-v-l4n959 .framer-f5khec { cursor: pointer; height: var(--framer-aspect-ratio-supported, 38px); width: 141px; }",
	".framer-Luar2.framer-v-l4n959 .framer-18kiu0w { flex: none; flex-direction: column; gap: 16px; overflow: visible; width: 100%; }",
	".framer-Luar2.framer-v-8vgg4f.framer-389x50 { gap: 20px; }",
	".framer-Luar2.framer-v-8vgg4f .framer-fzdypl { flex: none; padding: 4px 4px 4px 12px; width: min-content; }",
	".framer-Luar2.framer-v-8vgg4f .framer-18kiu0w { flex: none; width: min-content; }",
	".framer-Luar2.framer-v-1k9eonw .framer-b7ke7f { gap: 20px; padding: 4px 4px 4px 12px; }",
	".framer-Luar2.framer-v-wz6pu4 .framer-b7ke7f { gap: 16px; padding: 2px 2px 2px 6px; }",
	".framer-Luar2.framer-v-wz6pu4 .framer-f5khec { height: var(--framer-aspect-ratio-supported, 34px); width: 125px; }",
];
var Framerj8Sly2SM6 = withCSS2(Component2, css2, "framer-Luar2");
var stdin_default4 = Framerj8Sly2SM6;
Framerj8Sly2SM6.displayName = "Navigation";
Framerj8Sly2SM6.defaultProps = {
	height: 82,
	width: 1200,
};
addPropertyControls2(Framerj8Sly2SM6, {
	variant: {
		options: [
			"O8p5JbvBg",
			"MeTxynoL2",
			"avm8OLc_A",
			"ZMh3rRVPs",
			"tlHcUv3w4",
			"gfzXc5QXH",
			"vA5FUeUvu",
			"KMUe7lBtZ",
		],
		optionTitles: [
			"Desktop",
			"Tablet Close",
			"Tablet Open",
			"Phone Close",
			"Phone Open",
			"Desktop Scroll",
			"Tablet Scroll",
			"Phone Scroll",
		],
		title: "Variant",
		type: ControlType2.Enum,
	},
	ycH1W8s7_: {
		title: "Link",
		type: ControlType2.Link,
	},
});
addFonts2(
	Framerj8Sly2SM6,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...ButtonFonts,
		...CrossIconFonts,
		...MenuButtonFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:navigation
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "ZMh3rRVPs",
	md: "MeTxynoL2",
	xl: "O8p5JbvBg",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0ab435b455d76c767a5dea9600bc5786a15f10b45126633827329afa7ac48a86"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default4, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavigationFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0ab435b455d76c767a5dea9600bc5786a15f10b45126633827329afa7ac48a86"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default4}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default4);
var navigation_default = ComponentWithRoot;
export { navigation_default as default };
