// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0ab435b455d76c76 "Eventis (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * tag?: string // Tag
 * color?: string // Color
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-5D5Y4IKK.js";
import { routes } from "./chunks/chunk-MNEP7H2N.js";

// virtual:section-tag
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Section-Tag-dGhJ.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-TVkib";
var variantClassNames = {
	tdGjVnRv0: "framer-v-ioe750",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ color, height, id, tag, width, ...props }) => {
	return {
		...props,
		nx4Vg5CG3:
			color ??
			props.nx4Vg5CG3 ??
			"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))",
		zbD88MwBd: tag ?? props.zbD88MwBd ?? "Why Karyakram?",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		zbD88MwBd,
		nx4Vg5CG3,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "tdGjVnRv0",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-ioe750",
							className2,
							classNames,
						)}
						data-framer-name={"Tag"}
						layoutDependency={layoutDependency}
						layoutId={"tdGjVnRv0"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<motion.div
							className={"framer-1txi2gd"}
							data-framer-name={"Space"}
							layoutDependency={layoutDependency}
							layoutId={"et0tQdKrY"}
							style={{
								backgroundColor:
									"var(--token-c465f8c5-7fa9-436d-b203-2cb129c31fb1, rgb(237, 237, 237))",
							}}
						/>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-5zw0lw"}
							data-framer-name={"Why Karyakram?"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"JvAKxOBjz"}
							style={{
								"--extracted-1eung3n":
									"var(--variable-reference-nx4Vg5CG3-MyCFtZeQo)",
								"--framer-paragraph-spacing": "0px",
								"--variable-reference-nx4Vg5CG3-MyCFtZeQo": nx4Vg5CG3,
							}}
							text={zbD88MwBd}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.h4
									className={"framer-styles-preset-luad1x"}
									data-styles-preset={"QrpSGcou5"}
									style={{
										"--framer-text-color":
											"var(--extracted-1eung3n, var(--variable-reference-nx4Vg5CG3-MyCFtZeQo))",
									}}
								>
									{"Why Karyakram?"}
								</motion.h4>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-TVkib.framer-xwz8m5, .framer-TVkib .framer-xwz8m5 { display: block; }",
	".framer-TVkib.framer-ioe750 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 218px; }",
	".framer-TVkib .framer-1txi2gd { aspect-ratio: 9 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 4px); position: relative; width: 36px; }",
	".framer-TVkib .framer-5zw0lw { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-TVkib.framer-ioe750 { gap: 0px; } .framer-TVkib.framer-ioe750 > * { margin: 0px; margin-left: calc(8px / 2); margin-right: calc(8px / 2); } .framer-TVkib.framer-ioe750 > :first-child { margin-left: 0px; } .framer-TVkib.framer-ioe750 > :last-child { margin-right: 0px; } }",
	...css,
];
var FramerMyCFtZeQo = withCSS(Component, css2, "framer-TVkib");
var stdin_default = FramerMyCFtZeQo;
FramerMyCFtZeQo.displayName = "Section Tag";
FramerMyCFtZeQo.defaultProps = {
	height: 25,
	width: 218,
};
addPropertyControls(FramerMyCFtZeQo, {
	zbD88MwBd: {
		defaultValue: "Why Karyakram?",
		displayTextArea: false,
		title: "Tag",
		type: ControlType.String,
	},
	nx4Vg5CG3: {
		defaultValue:
			'var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255)) /* {"name":"White 100"} */',
		title: "Color",
		type: ControlType.Color,
	},
});
addFonts(
	FramerMyCFtZeQo,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:section-tag
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0ab435b455d76c767a5dea9600bc5786a15f10b45126633827329afa7ac48a86"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SectionTagFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0ab435b455d76c767a5dea9600bc5786a15f10b45126633827329afa7ac48a86"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var section_tag_default = ComponentWithRoot;
export { section_tag_default as default };
