// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0ab435b455d76c76 "Eventis (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'White ' | 'Grey' | 'Phone' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * name?: string // Name
 * designation?: string // Designation
 * instagramLink?: string // Instagram Link
 * linkedinLink?: string // Linkedin Link
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-FDT2E2K3.js";
import { className, css, fonts } from "./chunks/chunk-545RPIJJ.js";
import { Icon } from "./chunks/chunk-BTSBQWPZ.js";
import { routes } from "./chunks/chunk-MNEP7H2N.js";

// virtual:speaker-cards
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Speaker-Cards-prXO.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var PhosphorFonts = getFonts(Icon);
var cycleOrder = ["E4SHx6fjb", "E40JttOYB", "TC8CzzGQ0"];
var serializationHash = "framer-KUjhD";
var variantClassNames = {
	E40JttOYB: "framer-v-1lbxdpv",
	E4SHx6fjb: "framer-v-wk0h6m",
	TC8CzzGQ0: "framer-v-1rej4e8",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.4,
	ease: [0.12, 0.23, 0.5, 1],
	type: "tween",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var transition2 = {
	bounce: 0.25,
	delay: 0,
	duration: 0.45,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 0.9,
	skewX: 0,
	skewY: 0,
	transition: transition2,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"White ": "E4SHx6fjb",
	Grey: "E40JttOYB",
	Phone: "TC8CzzGQ0",
};
var getProps = ({
	designation,
	height,
	id,
	image,
	instagramLink,
	linkedinLink,
	name1,
	width,
	...props
}) => {
	return {
		...props,
		nIvBNoSTH: designation ?? props.nIvBNoSTH ?? "CEO of Coca Cola",
		RFB6SvfoB: image ??
			props.RFB6SvfoB ?? {
				pixelHeight: 1200,
				pixelWidth: 1200,
				src: "https://framerusercontent.com/images/cFl24iPInxckRrL32eRgadp9ZJM.png?scale-down-to=512",
				srcSet:
					"https://framerusercontent.com/images/cFl24iPInxckRrL32eRgadp9ZJM.png?scale-down-to=512 512w,https://framerusercontent.com/images/cFl24iPInxckRrL32eRgadp9ZJM.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/cFl24iPInxckRrL32eRgadp9ZJM.png 1200w",
			},
		tM8THrjkl: instagramLink ?? props.tM8THrjkl,
		tyhjRkC9z: linkedinLink ?? props.tyhjRkC9z,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "E4SHx6fjb",
		ZnwXRPx3Z: name1 ?? props.ZnwXRPx3Z ?? "Alberto Fransico",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		RFB6SvfoB,
		ZnwXRPx3Z,
		nIvBNoSTH,
		tM8THrjkl,
		tyhjRkC9z,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "E4SHx6fjb",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEnter16texol = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		setVariant("E40JttOYB");
	});
	const onMouseLeave1jizqg2 = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: false,
		});
		setVariant("E4SHx6fjb");
	});
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-wk0h6m",
							className3,
							classNames,
						)}
						data-framer-name={"White "}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"E4SHx6fjb"}
						onMouseEnter={onMouseEnter16texol}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								E40JttOYB: {
									"data-framer-name": "Grey",
									onMouseLeave: onMouseLeave1jizqg2,
								},
								TC8CzzGQ0: {
									"data-framer-name": "Phone",
									"data-highlight": void 0,
									onMouseEnter: void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-52kxyc"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"JyKRYekZ8"}
							style={{
								borderBottomLeftRadius: 24,
								borderBottomRightRadius: 24,
								borderTopLeftRadius: 24,
								borderTopRightRadius: 24,
							}}
						>
							<Image
								as={"figure"}
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 435.5) - 0 - 531.6) / 2 +
												0 +
												0) +
											0,
									),
									sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
									...toResponsiveImage(RFB6SvfoB),
								}}
								className={"framer-1kwjq53"}
								data-framer-name={"Image"}
								layoutDependency={layoutDependency}
								layoutId={"UAhy2Td02"}
								style={{
									borderBottomLeftRadius: 24,
									borderBottomRightRadius: 24,
									borderTopLeftRadius: 24,
									borderTopRightRadius: 24,
									filter: "grayscale(1)",
									WebkitFilter: "grayscale(1)",
								}}
								variants={{
									E40JttOYB: {
										filter: "grayscale(0)",
										WebkitFilter: "grayscale(0)",
									},
								}}
							>
								<Image
									as={"figure"}
									background={{
										alt: "",
										fit: "fill",
										intrinsicHeight: 265,
										intrinsicWidth: 285.5,
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 435.5) - 0 - 531.6) /
													2 +
													0 +
													0) +
												0 +
												354 -
												153,
										),
										pixelHeight: 530,
										pixelWidth: 571,
										sizes: "165px",
										src: "https://framerusercontent.com/images/Q38ypNMBsBVK6qjiF6kKfrobM24.png?scale-down-to=512",
										srcSet:
											"https://framerusercontent.com/images/Q38ypNMBsBVK6qjiF6kKfrobM24.png?scale-down-to=512 512w,https://framerusercontent.com/images/Q38ypNMBsBVK6qjiF6kKfrobM24.png 571w",
									}}
									className={"framer-509uuj"}
									data-framer-name={"Blue Blur"}
									layoutDependency={layoutDependency}
									layoutId={"sXrXjm5jQ"}
									{...addPropertyOverrides(
										{
											E40JttOYB: {
												background: {
													alt: "",
													fit: "fill",
													intrinsicHeight: 265,
													intrinsicWidth: 285.5,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															0 +
															(((componentViewport?.height || 435.5) -
																0 -
																531.6) /
																2 +
																0 +
																0) +
															0 +
															354 -
															195,
													),
													pixelHeight: 530,
													pixelWidth: 571,
													sizes: "210px",
													src: "https://framerusercontent.com/images/Q38ypNMBsBVK6qjiF6kKfrobM24.png?scale-down-to=512",
													srcSet:
														"https://framerusercontent.com/images/Q38ypNMBsBVK6qjiF6kKfrobM24.png?scale-down-to=512 512w,https://framerusercontent.com/images/Q38ypNMBsBVK6qjiF6kKfrobM24.png 571w",
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</Image>
							<Link
								href={tM8THrjkl}
								motionChild={true}
								nodeId={"nEVKprxZI"}
								scopeId={"CVWQChTHc"}
							>
								<motion.a
									className={"framer-1k1k4zw framer-y2mon8"}
									data-framer-name={"Instagram"}
									layoutDependency={layoutDependency}
									layoutId={"nEVKprxZI"}
									whileHover={animation}
									{...addPropertyOverrides(
										{
											TC8CzzGQ0: {
												whileHover: void 0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-1emtdt9-container"}
											isAuthoredByUser={true}
											isModuleExternal={true}
											layoutDependency={layoutDependency}
											layoutId={"VpS7mSFeM-container"}
											nodeId={"VpS7mSFeM"}
											rendersWithMotion={true}
											scopeId={"CVWQChTHc"}
										>
											<Icon
												color={
													"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))"
												}
												height={"100%"}
												iconSearch={"House"}
												iconSelection={"InstagramLogo"}
												id={"VpS7mSFeM"}
												layoutId={"VpS7mSFeM"}
												mirrored={false}
												selectByList={true}
												style={{
													height: "100%",
													width: "100%",
												}}
												weight={"fill"}
												width={"100%"}
											/>
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.a>
							</Link>
							<Link
								href={tyhjRkC9z}
								motionChild={true}
								nodeId={"yYLInznbs"}
								scopeId={"CVWQChTHc"}
							>
								<motion.a
									className={"framer-1kw927m framer-y2mon8"}
									data-framer-name={"Linkedin"}
									layoutDependency={layoutDependency}
									layoutId={"yYLInznbs"}
									whileHover={animation}
									{...addPropertyOverrides(
										{
											TC8CzzGQ0: {
												whileHover: void 0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-1itdr4f-container"}
											isAuthoredByUser={true}
											isModuleExternal={true}
											layoutDependency={layoutDependency}
											layoutId={"UTE6V3IkS-container"}
											nodeId={"UTE6V3IkS"}
											rendersWithMotion={true}
											scopeId={"CVWQChTHc"}
										>
											<Icon
												color={
													"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))"
												}
												height={"100%"}
												iconSearch={"House"}
												iconSelection={"LinkedinLogo"}
												id={"UTE6V3IkS"}
												layoutId={"UTE6V3IkS"}
												mirrored={false}
												selectByList={true}
												style={{
													height: "100%",
													width: "100%",
												}}
												weight={"fill"}
												width={"100%"}
											/>
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.a>
							</Link>
						</motion.div>
						<motion.div
							className={"framer-1dzgva6"}
							data-framer-name={"Profile"}
							layoutDependency={layoutDependency}
							layoutId={"OmH4ARRpo"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1ty9p1w"}
								data-framer-name={"Name"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"EZ_0RBFUN"}
								style={{
									"--extracted-1eung3n":
										"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={ZnwXRPx3Z}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h4
										className={"framer-styles-preset-quy3e0"}
										data-styles-preset={"zjIZS4r46"}
										style={{
											"--framer-text-color":
												"var(--extracted-1eung3n, var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255)))",
										}}
									>
										{"Alberto Fransico"}
									</motion.h4>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-15duqpu"}
								data-framer-name={"Designation"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"XaTCMl9SX"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-a1a0c7e5-1e4d-414c-8dba-5e69e14eca12, rgb(138, 138, 138))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={nIvBNoSTH}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-dsr0r"}
										data-styles-preset={"Erxl6HnxD"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-a1a0c7e5-1e4d-414c-8dba-5e69e14eca12, rgb(138, 138, 138)))",
										}}
									>
										{"CEO of Coca Cola"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-KUjhD.framer-y2mon8, .framer-KUjhD .framer-y2mon8 { display: block; }",
	".framer-KUjhD.framer-wk0h6m { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 315px; }",
	".framer-KUjhD .framer-52kxyc { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-KUjhD .framer-1kwjq53 { aspect-ratio: 0.8898305084745762 / 1; flex: 1 0 0px; height: var(--framer-aspect-ratio-supported, 354px); position: relative; width: 1px; }",
	".framer-KUjhD .framer-509uuj { aspect-ratio: 1.0773584905660378 / 1; bottom: 0px; flex: none; height: var(--framer-aspect-ratio-supported, 153px); overflow: visible; position: absolute; right: 0px; width: 165px; }",
	".framer-KUjhD .framer-1k1k4zw { align-content: center; align-items: center; aspect-ratio: 1 / 1; bottom: 16px; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 40px); justify-content: center; overflow: visible; padding: 0px; position: absolute; right: 66px; text-decoration: none; width: 40px; will-change: var(--framer-will-change-effect-override, transform); }",
	".framer-KUjhD .framer-1emtdt9-container, .framer-KUjhD .framer-1itdr4f-container { flex: 1 0 0px; height: 100%; position: relative; width: 1px; z-index: 1; }",
	".framer-KUjhD .framer-1kw927m { align-content: center; align-items: center; aspect-ratio: 1 / 1; bottom: 16px; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 40px); justify-content: center; overflow: visible; padding: 0px; position: absolute; right: 17px; text-decoration: none; width: 40px; will-change: var(--framer-will-change-effect-override, transform); }",
	".framer-KUjhD .framer-1dzgva6 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-KUjhD .framer-1ty9p1w, .framer-KUjhD .framer-15duqpu { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-KUjhD.framer-v-1lbxdpv .framer-509uuj { height: var(--framer-aspect-ratio-supported, 195px); width: 210px; }",
	".framer-KUjhD.framer-v-1rej4e8 .framer-1k1k4zw, .framer-KUjhD.framer-v-1rej4e8 .framer-1kw927m { will-change: unset; }",
	...css2,
	...css,
];
var FramerCVWQChTHc = withCSS(Component, css3, "framer-KUjhD");
var stdin_default = FramerCVWQChTHc;
FramerCVWQChTHc.displayName = "Speaker Cards";
FramerCVWQChTHc.defaultProps = {
	height: 435.5,
	width: 315,
};
addPropertyControls(FramerCVWQChTHc, {
	variant: {
		options: ["E4SHx6fjb", "E40JttOYB", "TC8CzzGQ0"],
		optionTitles: ["White ", "Grey", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	RFB6SvfoB: {
		__defaultAssetReference:
			"data:framer/asset-reference,cFl24iPInxckRrL32eRgadp9ZJM.png?originalFilename=QmdhQ1ysJFGNZm4DQNEXV1LDrV1zvNkeaPWoVmzFaRLJ7R%3Fauto%3Dformat%26h%3D1200.png&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	ZnwXRPx3Z: {
		defaultValue: "Alberto Fransico",
		displayTextArea: false,
		title: "Name",
		type: ControlType.String,
	},
	nIvBNoSTH: {
		defaultValue: "CEO of Coca Cola",
		displayTextArea: false,
		title: "Designation",
		type: ControlType.String,
	},
	tM8THrjkl: {
		title: "Instagram Link",
		type: ControlType.Link,
	},
	tyhjRkC9z: {
		title: "Linkedin Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerCVWQChTHc,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PhosphorFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:speaker-cards
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "E4SHx6fjb",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0ab435b455d76c767a5dea9600bc5786a15f10b45126633827329afa7ac48a86"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SpeakerCardsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0ab435b455d76c767a5dea9600bc5786a15f10b45126633827329afa7ac48a86"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var speaker_cards_default = ComponentWithRoot;
export { speaker_cards_default as default };
