// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0ab435b455d76c76 "Eventis (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Loading' | 'Disabled' | 'Success' | 'Error' | 'Phone' // Variant
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-DD6C4KVC.js";
import { routes } from "./chunks/chunk-MNEP7H2N.js";

// virtual:submit-button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Submit-Button-7WSz.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFX = withFX(motion.div);
var enabledGestures = {
	sR8uaJmvU: {
		hover: true,
		pressed: true,
	},
};
var cycleOrder = [
	"sR8uaJmvU",
	"HsLliaHmA",
	"MWO5PjDFA",
	"jLwjSMWpk",
	"wbYWinPat",
	"JxchebADB",
];
var serializationHash = "framer-96F3A";
var variantClassNames = {
	HsLliaHmA: "framer-v-19b0nvk",
	jLwjSMWpk: "framer-v-16o4wzl",
	JxchebADB: "framer-v-ue1qcw",
	MWO5PjDFA: "framer-v-knhgq5",
	sR8uaJmvU: "framer-v-1c57ea3",
	wbYWinPat: "framer-v-1gve4ty",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.4,
	ease: [0.12, 0.23, 0.5, 1],
	type: "tween",
};
var transition2 = {
	delay: 0,
	duration: 0.5,
	ease: [0.12, 0.23, 0.5, 1],
	type: "tween",
};
var transition3 = {
	delay: 0,
	duration: 1,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 360,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "sR8uaJmvU",
	Disabled: "MWO5PjDFA",
	Error: "wbYWinPat",
	Loading: "HsLliaHmA",
	Phone: "JxchebADB",
	Success: "jLwjSMWpk",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "sR8uaJmvU",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "sR8uaJmvU",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "HsLliaHmA") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "HsLliaHmA") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition
					value={transition1}
					{...addPropertyOverrides(
						{
							"sR8uaJmvU-hover": {
								value: transition2,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion.button
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1c57ea3",
							className2,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Default"}
						data-reset={"button"}
						layoutDependency={layoutDependency}
						layoutId={"sR8uaJmvU"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-f1c81b52-2a59-4da2-a47f-3f4bfb2f2b58, rgb(1, 30, 255))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))",
							borderBottomLeftRadius: 999,
							borderBottomRightRadius: 999,
							borderTopLeftRadius: 999,
							borderTopRightRadius: 999,
							boxShadow: "none",
							opacity: 1,
							...style,
						}}
						variants={{
							"sR8uaJmvU-hover": {
								"--border-color":
									"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))",
								backgroundColor:
									"var(--token-f1c81b52-2a59-4da2-a47f-3f4bfb2f2b58, rgb(1, 30, 255))",
								boxShadow: "none",
								opacity: 1,
							},
							"sR8uaJmvU-pressed": {
								boxShadow: "none",
								opacity: 1,
							},
							jLwjSMWpk: {
								opacity: 1,
							},
							JxchebADB: {
								boxShadow: "none",
								opacity: 1,
							},
							MWO5PjDFA: {
								opacity: 0.5,
							},
							wbYWinPat: {
								"--border-color":
									"var(--token-3f7ab7b0-88eb-47f2-ab4d-dd4761361ee0, rgb(255, 34, 68))",
								boxShadow:
									"-12px 0px 21px -3px var(--token-3a5ebd19-1975-41f4-a3b4-f278efe98054, rgb(255, 34, 68)), -7px 0px 10px -5px rgb(255, 56, 132)",
								opacity: 1,
							},
						}}
						{...addPropertyOverrides(
							{
								"sR8uaJmvU-hover": {
									"data-framer-name": void 0,
								},
								"sR8uaJmvU-pressed": {
									"data-framer-name": void 0,
								},
								HsLliaHmA: {
									"data-framer-name": "Loading",
								},
								jLwjSMWpk: {
									"data-framer-name": "Success",
								},
								JxchebADB: {
									"data-framer-name": "Phone",
								},
								MWO5PjDFA: {
									"data-framer-name": "Disabled",
								},
								wbYWinPat: {
									"data-framer-name": "Error",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1gio027"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"cXCEpl4P3"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								variants={{
									"sR8uaJmvU-hover": {
										"--extracted-r6o4lv":
											"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))",
									},
									jLwjSMWpk: {
										"--extracted-r6o4lv":
											"var(--token-440020f8-b9e1-49ea-9687-1ea12b43b3de, rgb(0, 0, 0))",
									},
									wbYWinPat: {
										"--extracted-r6o4lv":
											"var(--token-3f7ab7b0-88eb-47f2-ab4d-dd4761361ee0, rgb(255, 34, 68))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										"sR8uaJmvU-hover": {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1xv2ouf"}
														data-styles-preset={"WA7YBUoWN"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255)))",
														}}
													>
														{"Submit"}
													</motion.p>
												</React.Fragment>
											),
										},
										jLwjSMWpk: {
											children: (
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "RlM7UG9wcGlucy1zZW1pYm9sZA==",
															"--framer-font-family":
																'"Poppins", "Poppins Placeholder", sans-serif',
															"--framer-font-size": "14px",
															"--framer-font-weight": "600",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-440020f8-b9e1-49ea-9687-1ea12b43b3de, rgb(0, 0, 0)))",
														}}
													>
														{"Thank you"}
													</motion.p>
												</React.Fragment>
											),
											fonts: ["FS;Poppins-semibold"],
										},
										wbYWinPat: {
											children: (
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "RlM7UG9wcGlucy1zZW1pYm9sZA==",
															"--framer-font-family":
																'"Poppins", "Poppins Placeholder", sans-serif',
															"--framer-font-size": "14px",
															"--framer-font-weight": "600",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-3f7ab7b0-88eb-47f2-ab4d-dd4761361ee0, rgb(255, 34, 68)))",
														}}
													>
														{"Someting went wrong"}
													</motion.p>
												</React.Fragment>
											),
											fonts: ["FS;Poppins-semibold"],
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1xv2ouf"}
										data-styles-preset={"WA7YBUoWN"}
									>
										{"Submit"}
									</motion.p>
								</React.Fragment>
							</RichText>
						)}
						{isDisplayed1() && (
							<motion.div
								className={"framer-1aqzcxf"}
								data-framer-name={"Spinner"}
								layoutDependency={layoutDependency}
								layoutId={"LCNUfBGGF"}
								style={{
									mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add",
									WebkitMask:
										"url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add",
								}}
							>
								<MotionDivWithFX
									__framer__loop={animation}
									__framer__loopEffectEnabled={true}
									__framer__loopRepeatDelay={0}
									__framer__loopRepeatType={"loop"}
									__framer__loopTransition={transition3}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-1s11gbx"}
									data-framer-name={"Conic"}
									layoutDependency={layoutDependency}
									layoutId={"PVE3MpTSU"}
									style={{
										backgroundColor:
											"var(--token-d87dc5f7-2638-4b77-9368-a8568c56fcca, rgb(38, 38, 38))",
									}}
								>
									<motion.div
										className={"framer-14zye2k"}
										data-framer-name={"Rounding"}
										layoutDependency={layoutDependency}
										layoutId={"UkGCYQ3XP"}
										style={{
											backgroundColor:
												"var(--token-9a7303fe-2324-4aa1-bbd4-e1f1d449de82, rgba(255, 255, 255, 0.12))",
											borderBottomLeftRadius: 1,
											borderBottomRightRadius: 1,
											borderTopLeftRadius: 1,
											borderTopRightRadius: 1,
										}}
										transformTemplate={transformTemplate1}
									/>
								</MotionDivWithFX>
							</motion.div>
						)}
					</motion.button>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-96F3A.framer-1e2qtz, .framer-96F3A .framer-1e2qtz { display: block; }",
	".framer-96F3A.framer-1c57ea3 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 40px; justify-content: center; overflow: visible; padding: 6px 6px 6px 16px; position: relative; width: 240px; }",
	".framer-96F3A .framer-1gio027 { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-96F3A .framer-1aqzcxf { aspect-ratio: 1 / 1; flex: none; gap: 10px; height: var(--framer-aspect-ratio-supported, 20px); overflow: hidden; position: relative; width: 20px; }",
	".framer-96F3A .framer-1s11gbx { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
	".framer-96F3A .framer-14zye2k { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 9px); left: 50%; overflow: visible; position: absolute; top: 0px; width: 10px; }",
	".framer-96F3A.framer-v-19b0nvk.framer-1c57ea3, .framer-96F3A.framer-v-knhgq5.framer-1c57ea3, .framer-96F3A.framer-v-16o4wzl.framer-1c57ea3, .framer-96F3A.framer-v-1gve4ty.framer-1c57ea3, .framer-96F3A.framer-v-ue1qcw.framer-1c57ea3 { cursor: unset; }",
	".framer-96F3A.framer-v-19b0nvk .framer-14zye2k { height: var(--framer-aspect-ratio-supported, 10px); }",
	...css,
	'.framer-96F3A[data-border="true"]::after, .framer-96F3A [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var Framerck6MnBDfu = withCSS(Component, css2, "framer-96F3A");
var stdin_default = Framerck6MnBDfu;
Framerck6MnBDfu.displayName = "Submit Button";
Framerck6MnBDfu.defaultProps = {
	height: 40,
	width: 240,
};
addPropertyControls(Framerck6MnBDfu, {
	variant: {
		options: [
			"sR8uaJmvU",
			"HsLliaHmA",
			"MWO5PjDFA",
			"jLwjSMWpk",
			"wbYWinPat",
			"JxchebADB",
		],
		optionTitles: [
			"Default",
			"Loading",
			"Disabled",
			"Success",
			"Error",
			"Phone",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	Framerck6MnBDfu,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Poppins",
					source: "fontshare",
					style: "normal",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/E6J4GS76KHNRRUWODFCFOX2JRKNRSFVY/3GYVT5S4AH7VMPASDDKOTIPV6P3WJXGI/24R4YOH3G2SFDSTCNHOVGYEX3DMRC3CE.woff2",
					weight: "600",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:submit-button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "JxchebADB",
	xl: "sR8uaJmvU",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0ab435b455d76c767a5dea9600bc5786a15f10b45126633827329afa7ac48a86"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SubmitButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0ab435b455d76c767a5dea9600bc5786a15f10b45126633827329afa7ac48a86"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var submit_button_default = ComponentWithRoot;
export { submit_button_default as default };
