// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0ab435b455d76c76 "Eventis (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop 1' | 'Desktop 2' | 'Desktop 3' | 'Desktop 4' | 'Tablet 1' | 'Tablet 2' | 'Tablet 3' | 'Tablet 4' | 'Phone 1' | 'Phone 2' | 'Phone 3' | 'Phone 4' // Variant
 * businessMan?: string // Business man
 * investors?: string // Investors
 * founders?: string // Founders
 * developers?: string // Developers
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-LSJUZZSK.js";
import { className, css, fonts } from "./chunks/chunk-545RPIJJ.js";
import { Icon } from "./chunks/chunk-BTSBQWPZ.js";
import { routes } from "./chunks/chunk-MNEP7H2N.js";

// virtual:whom-card
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Whom-Card-OCp4.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType2,
	cx as cx2,
	getFonts as getFonts2,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	RichText as RichText2,
	SmartComponentScopedContainer as SmartComponentScopedContainer2,
	useActiveVariantCallback as useActiveVariantCallback2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/MlnhckiSo6umJsjPTwR1/PiHWf8NUDbJBZhPJFZV7/FuSVYdjkq.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	getPropertyControls,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ImageWithFX = withFX(Image);
var PhosphorFonts = getFonts(Icon);
var PhosphorControls = getPropertyControls(Icon);
var enabledGestures = {
	MYPnSQ3s_: {
		hover: true,
	},
};
var cycleOrder = ["MYPnSQ3s_", "mM6kM0ujm", "cPXbqmD5R"];
var serializationHash = "framer-kUHcv";
var variantClassNames = {
	cPXbqmD5R: "framer-v-q3byp3",
	mM6kM0ujm: "framer-v-1wn31oz",
	MYPnSQ3s_: "framer-v-6klljf",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.4,
	ease: [0.12, 0.23, 0.5, 1],
	type: "tween",
};
var transition2 = {
	delay: 0,
	duration: 16,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 360,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableEnumMap = {
	Bold: "bold",
	Duotone: "duotone",
	Fill: "fill",
	Light: "light",
	Regular: "regular",
	Thin: "thin",
};
var humanReadableVariantMap = {
	"Phone Square": "cPXbqmD5R",
	Clicked: "mM6kM0ujm",
	Square: "MYPnSQ3s_",
};
var getProps = ({
	_01Label,
	click,
	height,
	icon,
	id,
	weight,
	width,
	...props
}) => {
	return {
		...props,
		Dt4dt7HqR: icon ?? props.Dt4dt7HqR ?? "Briefcase",
		Dwt4Su0Ru: click ?? props.Dwt4Su0Ru,
		fnbXJPVPP:
			humanReadableEnumMap[weight] ?? weight ?? props.fnbXJPVPP ?? "light",
		V3mVfgAGp: _01Label ?? props.V3mVfgAGp ?? "Business Man",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "MYPnSQ3s_",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		Dwt4Su0Ru,
		V3mVfgAGp,
		Dt4dt7HqR,
		fnbXJPVPP,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "MYPnSQ3s_",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapyyktyf = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (Dwt4Su0Ru) {
			const res = await Dwt4Su0Ru(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-6klljf",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Square"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"MYPnSQ3s_"}
						onTap={onTapyyktyf}
						ref={refBinding}
						style={{
							"--border-bottom-width": "2px",
							"--border-color":
								"var(--token-d87dc5f7-2638-4b77-9368-a8568c56fcca, rgb(38, 38, 38))",
							"--border-left-width": "2px",
							"--border-right-width": "2px",
							"--border-style": "solid",
							"--border-top-width": "2px",
							borderBottomLeftRadius: 70,
							borderBottomRightRadius: 70,
							borderTopLeftRadius: 70,
							borderTopRightRadius: 70,
							...style,
						}}
						variants={{
							"MYPnSQ3s_-hover": {
								"--border-color":
									"var(--token-f1e2c775-aff6-494c-a201-646657d66935, rgb(36, 83, 255))",
							},
							cPXbqmD5R: {
								borderBottomLeftRadius: 35,
								borderBottomRightRadius: 35,
								borderTopLeftRadius: 35,
								borderTopRightRadius: 35,
							},
							mM6kM0ujm: {
								"--border-color":
									"var(--token-f1c81b52-2a59-4da2-a47f-3f4bfb2f2b58, rgb(1, 30, 255))",
								borderBottomLeftRadius: 9999,
								borderBottomRightRadius: 9999,
								borderTopLeftRadius: 9999,
								borderTopRightRadius: 9999,
							},
						}}
						{...addPropertyOverrides(
							{
								"MYPnSQ3s_-hover": {
									"data-framer-name": void 0,
								},
								cPXbqmD5R: {
									"data-framer-name": "Phone Square",
								},
								mM6kM0ujm: {
									"data-framer-name": "Clicked",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ImageWithFX
							__framer__loop={animation}
							__framer__loopEffectEnabled={true}
							__framer__loopPauseOffscreen={true}
							__framer__loopRepeatDelay={0}
							__framer__loopRepeatType={"loop"}
							__framer__loopTransition={transition2}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 427.5,
								intrinsicWidth: 427.5,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										((componentViewport?.height || 244) * 0.5000000000000002 -
											((componentViewport?.height || 244) * 0.623) / 2),
								),
								pixelHeight: 855,
								pixelWidth: 855,
								sizes: `calc(${componentViewport?.width || "100vw"} * 0.623)`,
								src: "https://framerusercontent.com/images/wX62SMRMN1v1X6SFoJaoNdwo.webp?scale-down-to=512",
								srcSet:
									"https://framerusercontent.com/images/wX62SMRMN1v1X6SFoJaoNdwo.webp?scale-down-to=512 512w,https://framerusercontent.com/images/wX62SMRMN1v1X6SFoJaoNdwo.webp 855w",
							}}
							className={"framer-vdq0vg"}
							data-framer-name={"Cube"}
							layoutDependency={layoutDependency}
							layoutId={"BZfnWCjsT"}
							style={{
								filter: "contrast(1.26)",
								WebkitFilter: "contrast(1.26)",
							}}
							{...addPropertyOverrides(
								{
									mM6kM0ujm: {
										background: {
											alt: "",
											fit: "fill",
											intrinsicHeight: 427.5,
											intrinsicWidth: 427.5,
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													((componentViewport?.height || 244) *
														0.5000000000000002 -
														((componentViewport?.height || 244) * 1) / 2),
											),
											pixelHeight: 855,
											pixelWidth: 855,
											sizes: componentViewport?.width || "100vw",
											src: "https://framerusercontent.com/images/wX62SMRMN1v1X6SFoJaoNdwo.webp?scale-down-to=512",
											srcSet:
												"https://framerusercontent.com/images/wX62SMRMN1v1X6SFoJaoNdwo.webp?scale-down-to=512 512w,https://framerusercontent.com/images/wX62SMRMN1v1X6SFoJaoNdwo.webp 855w",
										},
									},
								},
								baseVariant,
								gestureVariant,
							)}
						/>
						<motion.div
							className={"framer-dr18ap"}
							layoutDependency={layoutDependency}
							layoutId={"F_O9UVuIb"}
							style={{
								backdropFilter: "blur(5px)",
								backgroundColor:
									"var(--token-440020f8-b9e1-49ea-9687-1ea12b43b3de, rgb(0, 0, 0))",
								WebkitBackdropFilter: "blur(5px)",
							}}
							variants={{
								mM6kM0ujm: {
									backdropFilter: "blur(8px)",
									backgroundColor:
										"var(--token-7efc4de7-b212-4a26-bc9f-5cab4b89f6fd, rgba(0, 0, 0, 0.52))",
									WebkitBackdropFilter: "blur(8px)",
								},
							}}
						/>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-12hi9of-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"m6QPy38RG-container"}
								nodeId={"m6QPy38RG"}
								rendersWithMotion={true}
								scopeId={"FuSVYdjkq"}
							>
								<Icon
									color={
										"var(--token-a1a0c7e5-1e4d-414c-8dba-5e69e14eca12, rgb(138, 138, 138))"
									}
									height={"100%"}
									iconSearch={"House"}
									iconSelection={Dt4dt7HqR}
									id={"m6QPy38RG"}
									layoutId={"m6QPy38RG"}
									mirrored={false}
									selectByList={true}
									style={{
										height: "100%",
										width: "100%",
									}}
									weight={"light"}
									width={"100%"}
									{...addPropertyOverrides(
										{
											mM6kM0ujm: {
												color:
													"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))",
												weight: fnbXJPVPP,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-31nozc"}
							data-framer-name={"Business Man"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"vUsixasvy"}
							style={{
								"--extracted-1eung3n":
									"var(--token-a1a0c7e5-1e4d-414c-8dba-5e69e14eca12, rgb(138, 138, 138))",
								"--framer-paragraph-spacing": "0px",
							}}
							text={V3mVfgAGp}
							variants={{
								mM6kM0ujm: {
									"--extracted-1eung3n":
										"var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255))",
								},
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									mM6kM0ujm: {
										children: (
											<React.Fragment>
												<motion.h4
													className={"framer-styles-preset-flhrrz"}
													data-styles-preset={"dgjyWRW1V"}
													style={{
														"--framer-text-alignment": "center",
														"--framer-text-color":
															"var(--extracted-1eung3n, var(--token-873fb35c-2084-47f0-9254-cb5d8b65f475, rgb(255, 255, 255)))",
													}}
												>
													{"Business Man"}
												</motion.h4>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.h4
									className={"framer-styles-preset-flhrrz"}
									data-styles-preset={"dgjyWRW1V"}
									style={{
										"--framer-text-alignment": "center",
										"--framer-text-color":
											"var(--extracted-1eung3n, var(--token-a1a0c7e5-1e4d-414c-8dba-5e69e14eca12, rgb(138, 138, 138)))",
									}}
								>
									{"Business Man"}
								</motion.h4>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-kUHcv.framer-qtjyk3, .framer-kUHcv .framer-qtjyk3 { display: block; }",
	".framer-kUHcv.framer-6klljf { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 244px; justify-content: center; overflow: hidden; padding: 20px; position: relative; width: 244px; will-change: var(--framer-will-change-override, transform); }",
	".framer-kUHcv .framer-vdq0vg { flex: none; height: 62%; left: calc(50.00000000000002% - 62.295081967213115% / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 62.295081967213115% / 2); width: 62%; }",
	".framer-kUHcv .framer-dr18ap { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 244px); left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; }",
	".framer-kUHcv .framer-12hi9of-container { flex: none; height: 60px; position: relative; width: 60px; }",
	".framer-kUHcv .framer-31nozc { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-kUHcv.framer-v-1wn31oz.framer-6klljf, .framer-kUHcv.framer-v-q3byp3.framer-6klljf, .framer-kUHcv.framer-v-6klljf.hover.framer-6klljf { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 244px); }",
	".framer-kUHcv.framer-v-1wn31oz .framer-vdq0vg { height: 100%; left: calc(50.00000000000002% - 100% / 2); order: 0; top: calc(50.00000000000002% - 100% / 2); width: 100%; }",
	".framer-kUHcv.framer-v-1wn31oz .framer-dr18ap { order: 1; }",
	".framer-kUHcv.framer-v-1wn31oz .framer-12hi9of-container { order: 2; }",
	".framer-kUHcv.framer-v-1wn31oz .framer-31nozc { order: 3; }",
	...css2,
	'.framer-kUHcv[data-border="true"]::after, .framer-kUHcv [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerFuSVYdjkq = withCSS(Component, css3, "framer-kUHcv");
var stdin_default = FramerFuSVYdjkq;
FramerFuSVYdjkq.displayName = "Polygons";
FramerFuSVYdjkq.defaultProps = {
	height: 244,
	width: 244,
};
addPropertyControls(FramerFuSVYdjkq, {
	variant: {
		options: ["MYPnSQ3s_", "mM6kM0ujm", "cPXbqmD5R"],
		optionTitles: ["Square", "Clicked", "Phone Square"],
		title: "Variant",
		type: ControlType.Enum,
	},
	Dwt4Su0Ru: {
		title: "Click",
		type: ControlType.EventHandler,
	},
	V3mVfgAGp: {
		defaultValue: "Business Man",
		displayTextArea: false,
		title: "01 Label",
		type: ControlType.String,
	},
	Dt4dt7HqR: PhosphorControls?.["iconSelection"] && {
		...PhosphorControls["iconSelection"],
		defaultValue: "Briefcase",
		description: void 0,
		hidden: void 0,
		title: "Icon",
	},
	fnbXJPVPP: PhosphorControls?.["weight"] && {
		...PhosphorControls["weight"],
		defaultValue: "light",
		description: void 0,
		hidden: void 0,
		title: "Weight",
	},
});
addFonts(
	FramerFuSVYdjkq,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PhosphorFonts,
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framer.com/m/Whom-Card-OCp4.js
var PolygonsFonts = getFonts2(stdin_default);
var cycleOrder2 = [
	"Bhf7mgZFO",
	"DUNJaa_2U",
	"Vzk9SujVN",
	"Bh0KC_eZ8",
	"xYtUMozi0",
	"Oq2rHCdCh",
	"Ts3BiCBo9",
	"kuzZryZVE",
	"j8w88SHnc",
	"d9Fsj5WpK",
	"jVCEOzxXJ",
	"AUoTRH9MD",
];
var serializationHash2 = "framer-G6Ndb";
var variantClassNames2 = {
	AUoTRH9MD: "framer-v-1jpj1gq",
	Bh0KC_eZ8: "framer-v-1dr5opv",
	Bhf7mgZFO: "framer-v-1mpnhrg",
	d9Fsj5WpK: "framer-v-14cm3v9",
	DUNJaa_2U: "framer-v-12454v9",
	j8w88SHnc: "framer-v-192p4h3",
	jVCEOzxXJ: "framer-v-12pc4n3",
	kuzZryZVE: "framer-v-65toer",
	Oq2rHCdCh: "framer-v-mzja4a",
	Ts3BiCBo9: "framer-v-omuf8b",
	Vzk9SujVN: "framer-v-1ubwpww",
	xYtUMozi0: "framer-v-1eya49f",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	delay: 0,
	duration: 0.4,
	ease: [0.12, 0.23, 0.5, 1],
	type: "tween",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	"Desktop 1": "Bhf7mgZFO",
	"Desktop 2": "DUNJaa_2U",
	"Desktop 3": "Vzk9SujVN",
	"Desktop 4": "Bh0KC_eZ8",
	"Phone 1": "j8w88SHnc",
	"Phone 2": "d9Fsj5WpK",
	"Phone 3": "jVCEOzxXJ",
	"Phone 4": "AUoTRH9MD",
	"Tablet 1": "xYtUMozi0",
	"Tablet 2": "Oq2rHCdCh",
	"Tablet 3": "Ts3BiCBo9",
	"Tablet 4": "kuzZryZVE",
};
var getProps2 = ({
	businessMan,
	developers,
	founders,
	height,
	id,
	investors,
	width,
	...props
}) => {
	return {
		...props,
		AOzSz5R2Y:
			developers ??
			props.AOzSz5R2Y ??
			"Explore powerful new frameworks, join immersive technical sessions, solve real-world problems with AI, and grow within a thriving dev community.",
		DICEOonaS:
			investors ??
			props.DICEOonaS ??
			"Identify breakthrough innovations, connect with disruptive startups, gain deep insights into AI trends, and uncover your next big opportunity.",
		EfD_tVDRE:
			businessMan ??
			props.EfD_tVDRE ??
			"Unlock AI\u2019s potential to optimize operations, enhance customer experiences, drive data-informed decisions, and stay competitive in a fast-evolving market.",
		HrCFO37Cw:
			founders ??
			props.HrCFO37Cw ??
			"Learn how to build smarter products, scale faster with AI-driven tools, refine your strategy with expert guidance, and meet future collaborators or backers.",
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "Bhf7mgZFO",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		EfD_tVDRE,
		DICEOonaS,
		HrCFO37Cw,
		AOzSz5R2Y,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "Bhf7mgZFO",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback2(baseVariant);
	const Dwt4Su0Ruv40r63 = activeVariantCallback(async (...args) => {
		setVariant("Bhf7mgZFO");
	});
	const Dwt4Su0Rusutdep = activeVariantCallback(async (...args) => {
		setVariant("xYtUMozi0");
	});
	const Dwt4Su0Rukbyl96 = activeVariantCallback(async (...args) => {
		setVariant("j8w88SHnc");
	});
	const Dwt4Su0Ru1jgnc5f = activeVariantCallback(async (...args) => {
		setVariant("DUNJaa_2U");
	});
	const Dwt4Su0Ru675ax8 = activeVariantCallback(async (...args) => {
		setVariant("Oq2rHCdCh");
	});
	const Dwt4Su0Ru1a5qfy4 = activeVariantCallback(async (...args) => {
		setVariant("d9Fsj5WpK");
	});
	const Dwt4Su0Ruw62bis = activeVariantCallback(async (...args) => {
		setVariant("Vzk9SujVN");
	});
	const Dwt4Su0Rucgoygr = activeVariantCallback(async (...args) => {
		setVariant("Ts3BiCBo9");
	});
	const Dwt4Su0Rubrkzo3 = activeVariantCallback(async (...args) => {
		setVariant("jVCEOzxXJ");
	});
	const Dwt4Su0Ru15gdi5f = activeVariantCallback(async (...args) => {
		setVariant("Bh0KC_eZ8");
	});
	const Dwt4Su0Ru19x4uf7 = activeVariantCallback(async (...args) => {
		setVariant("kuzZryZVE");
	});
	const Dwt4Su0Ru1kqyvga = activeVariantCallback(async (...args) => {
		setVariant("AUoTRH9MD");
	});
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1mpnhrg",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop 1"}
						layoutDependency={layoutDependency}
						layoutId={"Bhf7mgZFO"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								AUoTRH9MD: {
									"data-framer-name": "Phone 4",
								},
								Bh0KC_eZ8: {
									"data-framer-name": "Desktop 4",
								},
								d9Fsj5WpK: {
									"data-framer-name": "Phone 2",
								},
								DUNJaa_2U: {
									"data-framer-name": "Desktop 2",
								},
								j8w88SHnc: {
									"data-framer-name": "Phone 1",
								},
								jVCEOzxXJ: {
									"data-framer-name": "Phone 3",
								},
								kuzZryZVE: {
									"data-framer-name": "Tablet 4",
								},
								Oq2rHCdCh: {
									"data-framer-name": "Tablet 2",
								},
								Ts3BiCBo9: {
									"data-framer-name": "Tablet 3",
								},
								Vzk9SujVN: {
									"data-framer-name": "Desktop 3",
								},
								xYtUMozi0: {
									"data-framer-name": "Tablet 1",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-1crz8ec"}
							data-framer-name={"Images"}
							layoutDependency={layoutDependency}
							layoutId={"jLlCZ66m2"}
						>
							<motion2.div
								className={"framer-1wdo29"}
								data-framer-name={"1 and 2"}
								layoutDependency={layoutDependency}
								layoutId={"ZHxbTSRPJ"}
							>
								<ComponentViewportProvider2
									height={244}
									width={`max((max((${componentViewport?.width || "100vw"} - 48px) / 2, 1px) - 48px) / 2, 1px)`}
									y={
										(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 200) - 0 - 533.5) / 2 +
											0 +
											0) +
										48.75 +
										0
									}
									{...addPropertyOverrides2(
										{
											AUoTRH9MD: {
												width: `max((${componentViewport?.width || "100vw"} - 20px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 797.5) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0,
											},
											d9Fsj5WpK: {
												width: `max((${componentViewport?.width || "100vw"} - 20px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 797.5) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0,
											},
											j8w88SHnc: {
												width: `max((${componentViewport?.width || "100vw"} - 20px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 797.5) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0,
											},
											jVCEOzxXJ: {
												width: `max((${componentViewport?.width || "100vw"} - 20px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 797.5) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0,
											},
											kuzZryZVE: {
												width: `max((${componentViewport?.width || "100vw"} - 48px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 841.5) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0,
											},
											Oq2rHCdCh: {
												width: `max((${componentViewport?.width || "100vw"} - 48px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 841.5) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0,
											},
											Ts3BiCBo9: {
												width: `max((${componentViewport?.width || "100vw"} - 48px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 841.5) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0,
											},
											xYtUMozi0: {
												width: `max((${componentViewport?.width || "100vw"} - 48px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 841.5) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer2
										className={"framer-152dku5-container"}
										layoutDependency={layoutDependency}
										layoutId={"PbeHTANaq-container"}
										nodeId={"PbeHTANaq"}
										rendersWithMotion={true}
										scopeId={"Qn4oD_GJt"}
									>
										{_jsx2(stdin_default, {
											Dt4dt7HqR: "Briefcase",
											Dwt4Su0Ru: Dwt4Su0Ruv40r63,
											fnbXJPVPP: "fill",
											height: "100%",
											id: "PbeHTANaq",
											layoutId: "PbeHTANaq",
											style: {
												height: "100%",
												width: "100%",
											},
											V3mVfgAGp: "Business Man",
											variant: "mM6kM0ujm",
											width: "100%",
											...addPropertyOverrides2(
												{
													AUoTRH9MD: {
														Dwt4Su0Ru: Dwt4Su0Rukbyl96,
														variant: "cPXbqmD5R",
													},
													Bh0KC_eZ8: {
														variant: "MYPnSQ3s_",
													},
													d9Fsj5WpK: {
														Dwt4Su0Ru: Dwt4Su0Rukbyl96,
														variant: "cPXbqmD5R",
													},
													DUNJaa_2U: {
														variant: "MYPnSQ3s_",
													},
													j8w88SHnc: {
														Dwt4Su0Ru: Dwt4Su0Rukbyl96,
													},
													jVCEOzxXJ: {
														Dwt4Su0Ru: Dwt4Su0Rukbyl96,
														variant: "cPXbqmD5R",
													},
													kuzZryZVE: {
														Dwt4Su0Ru: Dwt4Su0Rusutdep,
														variant: "MYPnSQ3s_",
													},
													Oq2rHCdCh: {
														Dwt4Su0Ru: Dwt4Su0Rusutdep,
														variant: "MYPnSQ3s_",
													},
													Ts3BiCBo9: {
														Dwt4Su0Ru: Dwt4Su0Rusutdep,
														variant: "MYPnSQ3s_",
													},
													Vzk9SujVN: {
														variant: "MYPnSQ3s_",
													},
													xYtUMozi0: {
														Dwt4Su0Ru: Dwt4Su0Rusutdep,
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer2>
								</ComponentViewportProvider2>
								<ComponentViewportProvider2
									height={244}
									width={`max((max((${componentViewport?.width || "100vw"} - 48px) / 2, 1px) - 48px) / 2, 1px)`}
									y={
										(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 200) - 0 - 533.5) / 2 +
											0 +
											0) +
										48.75 +
										0
									}
									{...addPropertyOverrides2(
										{
											AUoTRH9MD: {
												width: `max((${componentViewport?.width || "100vw"} - 20px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 797.5) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0,
											},
											d9Fsj5WpK: {
												width: `max((${componentViewport?.width || "100vw"} - 20px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 797.5) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0,
											},
											j8w88SHnc: {
												width: `max((${componentViewport?.width || "100vw"} - 20px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 797.5) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0,
											},
											jVCEOzxXJ: {
												width: `max((${componentViewport?.width || "100vw"} - 20px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 797.5) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0,
											},
											kuzZryZVE: {
												width: `max((${componentViewport?.width || "100vw"} - 48px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 841.5) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0,
											},
											Oq2rHCdCh: {
												width: `max((${componentViewport?.width || "100vw"} - 48px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 841.5) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0,
											},
											Ts3BiCBo9: {
												width: `max((${componentViewport?.width || "100vw"} - 48px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 841.5) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0,
											},
											xYtUMozi0: {
												width: `max((${componentViewport?.width || "100vw"} - 48px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 841.5) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer2
										className={"framer-1o12ez3-container"}
										layoutDependency={layoutDependency}
										layoutId={"VltnUiQTO-container"}
										nodeId={"VltnUiQTO"}
										rendersWithMotion={true}
										scopeId={"Qn4oD_GJt"}
									>
										{_jsx2(stdin_default, {
											Dt4dt7HqR: "Money",
											Dwt4Su0Ru: Dwt4Su0Ru1jgnc5f,
											fnbXJPVPP: "light",
											height: "100%",
											id: "VltnUiQTO",
											layoutId: "VltnUiQTO",
											style: {
												height: "100%",
												width: "100%",
											},
											V3mVfgAGp: "Investors",
											variant: "MYPnSQ3s_",
											width: "100%",
											...addPropertyOverrides2(
												{
													AUoTRH9MD: {
														Dwt4Su0Ru: Dwt4Su0Ru1a5qfy4,
														variant: "cPXbqmD5R",
													},
													d9Fsj5WpK: {
														Dwt4Su0Ru: Dwt4Su0Ru1a5qfy4,
														fnbXJPVPP: "fill",
														variant: "mM6kM0ujm",
													},
													DUNJaa_2U: {
														fnbXJPVPP: "fill",
														variant: "mM6kM0ujm",
													},
													j8w88SHnc: {
														Dwt4Su0Ru: Dwt4Su0Ru1a5qfy4,
														variant: "cPXbqmD5R",
													},
													jVCEOzxXJ: {
														Dwt4Su0Ru: Dwt4Su0Ru1a5qfy4,
														variant: "cPXbqmD5R",
													},
													kuzZryZVE: {
														Dwt4Su0Ru: Dwt4Su0Ru675ax8,
													},
													Oq2rHCdCh: {
														Dwt4Su0Ru: Dwt4Su0Ru675ax8,
														fnbXJPVPP: "fill",
														variant: "mM6kM0ujm",
													},
													Ts3BiCBo9: {
														Dwt4Su0Ru: Dwt4Su0Ru675ax8,
													},
													xYtUMozi0: {
														Dwt4Su0Ru: Dwt4Su0Ru675ax8,
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer2>
								</ComponentViewportProvider2>
							</motion2.div>
							<motion2.div
								className={"framer-8lynpm"}
								data-framer-name={"3 and 4"}
								layoutDependency={layoutDependency}
								layoutId={"vvuPLOIA5"}
							>
								<ComponentViewportProvider2
									height={341.5}
									width={`max((max((${componentViewport?.width || "100vw"} - 48px) / 2, 1px) - 48px) / 2, 1px)`}
									y={
										(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 200) - 0 - 533.5) / 2 +
											0 +
											0) +
										0 +
										0
									}
									{...addPropertyOverrides2(
										{
											AUoTRH9MD: {
												width: `max((${componentViewport?.width || "100vw"} - 20px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 797.5) /
														2 +
														0 +
														0) +
													0 +
													264 +
													0,
											},
											d9Fsj5WpK: {
												width: `max((${componentViewport?.width || "100vw"} - 20px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 797.5) /
														2 +
														0 +
														0) +
													0 +
													264 +
													0,
											},
											j8w88SHnc: {
												width: `max((${componentViewport?.width || "100vw"} - 20px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 797.5) /
														2 +
														0 +
														0) +
													0 +
													264 +
													0,
											},
											jVCEOzxXJ: {
												width: `max((${componentViewport?.width || "100vw"} - 20px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 797.5) /
														2 +
														0 +
														0) +
													0 +
													264 +
													0,
											},
											kuzZryZVE: {
												width: `max((${componentViewport?.width || "100vw"} - 48px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 841.5) /
														2 +
														0 +
														0) +
													0 +
													292 +
													0,
											},
											Oq2rHCdCh: {
												width: `max((${componentViewport?.width || "100vw"} - 48px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 841.5) /
														2 +
														0 +
														0) +
													0 +
													292 +
													0,
											},
											Ts3BiCBo9: {
												width: `max((${componentViewport?.width || "100vw"} - 48px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 841.5) /
														2 +
														0 +
														0) +
													0 +
													292 +
													0,
											},
											xYtUMozi0: {
												width: `max((${componentViewport?.width || "100vw"} - 48px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 841.5) /
														2 +
														0 +
														0) +
													0 +
													292 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer2
										className={"framer-os3hma-container"}
										layoutDependency={layoutDependency}
										layoutId={"me8Bd5QUr-container"}
										nodeId={"me8Bd5QUr"}
										rendersWithMotion={true}
										scopeId={"Qn4oD_GJt"}
									>
										{_jsx2(stdin_default, {
											Dt4dt7HqR: "OfficeChair",
											Dwt4Su0Ru: Dwt4Su0Ruw62bis,
											fnbXJPVPP: "light",
											height: "100%",
											id: "me8Bd5QUr",
											layoutId: "me8Bd5QUr",
											style: {
												height: "100%",
												width: "100%",
											},
											V3mVfgAGp: "Founder",
											variant: "MYPnSQ3s_",
											width: "100%",
											...addPropertyOverrides2(
												{
													AUoTRH9MD: {
														Dwt4Su0Ru: Dwt4Su0Rubrkzo3,
														variant: "cPXbqmD5R",
													},
													d9Fsj5WpK: {
														Dwt4Su0Ru: Dwt4Su0Rubrkzo3,
														variant: "cPXbqmD5R",
													},
													j8w88SHnc: {
														Dwt4Su0Ru: Dwt4Su0Rubrkzo3,
														variant: "cPXbqmD5R",
													},
													jVCEOzxXJ: {
														Dwt4Su0Ru: Dwt4Su0Rubrkzo3,
														fnbXJPVPP: "fill",
														variant: "mM6kM0ujm",
													},
													kuzZryZVE: {
														Dwt4Su0Ru: Dwt4Su0Rucgoygr,
													},
													Oq2rHCdCh: {
														Dwt4Su0Ru: Dwt4Su0Rucgoygr,
													},
													Ts3BiCBo9: {
														Dwt4Su0Ru: Dwt4Su0Rucgoygr,
														fnbXJPVPP: "fill",
														variant: "mM6kM0ujm",
													},
													Vzk9SujVN: {
														fnbXJPVPP: "fill",
														variant: "mM6kM0ujm",
													},
													xYtUMozi0: {
														Dwt4Su0Ru: Dwt4Su0Rucgoygr,
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer2>
								</ComponentViewportProvider2>
								<ComponentViewportProvider2
									height={341.5}
									width={`max((max((${componentViewport?.width || "100vw"} - 48px) / 2, 1px) - 48px) / 2, 1px)`}
									y={
										(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 200) - 0 - 533.5) / 2 +
											0 +
											0) +
										0 +
										0
									}
									{...addPropertyOverrides2(
										{
											AUoTRH9MD: {
												width: `max((${componentViewport?.width || "100vw"} - 20px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 797.5) /
														2 +
														0 +
														0) +
													0 +
													264 +
													0,
											},
											d9Fsj5WpK: {
												width: `max((${componentViewport?.width || "100vw"} - 20px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 797.5) /
														2 +
														0 +
														0) +
													0 +
													264 +
													0,
											},
											j8w88SHnc: {
												width: `max((${componentViewport?.width || "100vw"} - 20px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 797.5) /
														2 +
														0 +
														0) +
													0 +
													264 +
													0,
											},
											jVCEOzxXJ: {
												width: `max((${componentViewport?.width || "100vw"} - 20px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 797.5) /
														2 +
														0 +
														0) +
													0 +
													264 +
													0,
											},
											kuzZryZVE: {
												width: `max((${componentViewport?.width || "100vw"} - 48px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 841.5) /
														2 +
														0 +
														0) +
													0 +
													292 +
													0,
											},
											Oq2rHCdCh: {
												width: `max((${componentViewport?.width || "100vw"} - 48px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 841.5) /
														2 +
														0 +
														0) +
													0 +
													292 +
													0,
											},
											Ts3BiCBo9: {
												width: `max((${componentViewport?.width || "100vw"} - 48px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 841.5) /
														2 +
														0 +
														0) +
													0 +
													292 +
													0,
											},
											xYtUMozi0: {
												width: `max((${componentViewport?.width || "100vw"} - 48px) / 2, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 841.5) /
														2 +
														0 +
														0) +
													0 +
													292 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer2
										className={"framer-1389moq-container"}
										layoutDependency={layoutDependency}
										layoutId={"KcxufYz_S-container"}
										nodeId={"KcxufYz_S"}
										rendersWithMotion={true}
										scopeId={"Qn4oD_GJt"}
									>
										{_jsx2(stdin_default, {
											Dt4dt7HqR: "Code",
											Dwt4Su0Ru: Dwt4Su0Ru15gdi5f,
											fnbXJPVPP: "light",
											height: "100%",
											id: "KcxufYz_S",
											layoutId: "KcxufYz_S",
											style: {
												height: "100%",
												width: "100%",
											},
											V3mVfgAGp: "Developers",
											variant: "MYPnSQ3s_",
											width: "100%",
											...addPropertyOverrides2(
												{
													AUoTRH9MD: {
														Dwt4Su0Ru: Dwt4Su0Ru1kqyvga,
														fnbXJPVPP: "fill",
														variant: "mM6kM0ujm",
													},
													Bh0KC_eZ8: {
														fnbXJPVPP: "fill",
														variant: "mM6kM0ujm",
													},
													d9Fsj5WpK: {
														Dwt4Su0Ru: Dwt4Su0Ru1kqyvga,
														variant: "cPXbqmD5R",
													},
													j8w88SHnc: {
														Dwt4Su0Ru: Dwt4Su0Ru1kqyvga,
														variant: "cPXbqmD5R",
													},
													jVCEOzxXJ: {
														Dwt4Su0Ru: Dwt4Su0Ru1kqyvga,
														variant: "cPXbqmD5R",
													},
													kuzZryZVE: {
														Dwt4Su0Ru: Dwt4Su0Ru19x4uf7,
														fnbXJPVPP: "fill",
														variant: "mM6kM0ujm",
													},
													Oq2rHCdCh: {
														Dwt4Su0Ru: Dwt4Su0Ru19x4uf7,
													},
													Ts3BiCBo9: {
														Dwt4Su0Ru: Dwt4Su0Ru19x4uf7,
													},
													xYtUMozi0: {
														Dwt4Su0Ru: Dwt4Su0Ru19x4uf7,
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer2>
								</ComponentViewportProvider2>
							</motion2.div>
						</motion2.div>
						<motion2.div
							className={"framer-296zja"}
							data-border={true}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"sn5XXbjt5"}
							style={{
								"--border-bottom-width": "2px",
								"--border-color":
									"var(--token-d87dc5f7-2638-4b77-9368-a8568c56fcca, rgb(38, 38, 38))",
								"--border-left-width": "2px",
								"--border-right-width": "2px",
								"--border-style": "solid",
								"--border-top-width": "2px",
								backgroundColor:
									"var(--token-440020f8-b9e1-49ea-9687-1ea12b43b3de, rgb(0, 0, 0))",
								borderBottomLeftRadius: 24,
								borderBottomRightRadius: 24,
								borderTopLeftRadius: 24,
								borderTopRightRadius: 24,
							}}
						>
							<RichText2
								__fromCanvasComponent={true}
								className={"framer-gfcum4"}
								data-framer-name={"Text"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"piklJuqs7"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-c465f8c5-7fa9-436d-b203-2cb129c31fb1, rgb(237, 237, 237))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={EfD_tVDRE}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides2(
									{
										AUoTRH9MD: {
											text: AOzSz5R2Y,
										},
										Bh0KC_eZ8: {
											children: (
												<React2.Fragment>
													<motion2.p
														className={"framer-styles-preset-dsr0r"}
														data-styles-preset={"Erxl6HnxD"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-c465f8c5-7fa9-436d-b203-2cb129c31fb1, rgb(237, 237, 237)))",
														}}
													>
														{
															"04 Developer how to get paid what you\u2019re worth without justifying your price, handle stressful sales calls confidently, and attract clients who value your work. The training covers: Learn how to get paid what you\u2019re worth without justifying your price, handle stressful sales "
														}
													</motion2.p>
												</React2.Fragment>
											),
											text: AOzSz5R2Y,
										},
										d9Fsj5WpK: {
											text: DICEOonaS,
										},
										DUNJaa_2U: {
											children: (
												<React2.Fragment>
													<motion2.p
														className={"framer-styles-preset-dsr0r"}
														data-styles-preset={"Erxl6HnxD"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-c465f8c5-7fa9-436d-b203-2cb129c31fb1, rgb(237, 237, 237)))",
														}}
													>
														{
															"02 Investor Learn how to get paid what you\u2019re worth without justifying your price, handle stressful sales calls confidently, and attract clients who value your work. The training covers: Learn how to get paid what you\u2019re worth without justifying your price, handle stressful sales "
														}
													</motion2.p>
												</React2.Fragment>
											),
											text: DICEOonaS,
										},
										jVCEOzxXJ: {
											text: HrCFO37Cw,
										},
										kuzZryZVE: {
											text: AOzSz5R2Y,
										},
										Oq2rHCdCh: {
											text: DICEOonaS,
										},
										Ts3BiCBo9: {
											text: HrCFO37Cw,
										},
										Vzk9SujVN: {
											children: (
												<React2.Fragment>
													<motion2.p
														className={"framer-styles-preset-dsr0r"}
														data-styles-preset={"Erxl6HnxD"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-c465f8c5-7fa9-436d-b203-2cb129c31fb1, rgb(237, 237, 237)))",
														}}
													>
														{
															"03 Founder Learn how to get paid what you\u2019re worth without justifying your price, handle stressful sales calls confidently, and attract clients who value your work. The training covers: Learn how to get paid what you\u2019re worth without justifying your price, handle stressful sales "
														}
													</motion2.p>
												</React2.Fragment>
											),
											text: HrCFO37Cw,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React2.Fragment>
									<motion2.p
										className={"framer-styles-preset-dsr0r"}
										data-styles-preset={"Erxl6HnxD"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-c465f8c5-7fa9-436d-b203-2cb129c31fb1, rgb(237, 237, 237)))",
										}}
									>
										{
											"Unlock AI\u2019s potential to optimize operations, enhance customer experiences, drive data-informed decisions, and stay competitive in a fast-evolving market."
										}
									</motion2.p>
								</React2.Fragment>
							</RichText2>
						</motion2.div>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-G6Ndb.framer-1v45nxc, .framer-G6Ndb .framer-1v45nxc { display: block; }",
	".framer-G6Ndb.framer-1mpnhrg { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1120px; }",
	".framer-G6Ndb .framer-1crz8ec { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-G6Ndb .framer-1wdo29, .framer-G6Ndb .framer-8lynpm { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-G6Ndb .framer-152dku5-container, .framer-G6Ndb .framer-1o12ez3-container, .framer-G6Ndb .framer-os3hma-container, .framer-G6Ndb .framer-1389moq-container { aspect-ratio: 1 / 1; flex: 1 0 0px; height: var(--framer-aspect-ratio-supported, 200px); position: relative; width: 1px; }",
	".framer-G6Ndb .framer-296zja { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 24px 32px 24px 32px; position: relative; width: 100%; }",
	".framer-G6Ndb .framer-gfcum4 { flex: 1 0 0px; height: auto; max-width: 750px; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-G6Ndb.framer-v-1eya49f.framer-1mpnhrg, .framer-G6Ndb.framer-v-mzja4a.framer-1mpnhrg, .framer-G6Ndb.framer-v-omuf8b.framer-1mpnhrg, .framer-G6Ndb.framer-v-65toer.framer-1mpnhrg { gap: 40px; width: 810px; }",
	".framer-G6Ndb.framer-v-1eya49f .framer-1crz8ec, .framer-G6Ndb.framer-v-mzja4a .framer-1crz8ec, .framer-G6Ndb.framer-v-omuf8b .framer-1crz8ec, .framer-G6Ndb.framer-v-65toer .framer-1crz8ec { flex-direction: column; }",
	".framer-G6Ndb.framer-v-1eya49f .framer-1wdo29, .framer-G6Ndb.framer-v-1eya49f .framer-8lynpm, .framer-G6Ndb.framer-v-mzja4a .framer-1wdo29, .framer-G6Ndb.framer-v-mzja4a .framer-8lynpm, .framer-G6Ndb.framer-v-omuf8b .framer-1wdo29, .framer-G6Ndb.framer-v-omuf8b .framer-8lynpm, .framer-G6Ndb.framer-v-65toer .framer-1wdo29, .framer-G6Ndb.framer-v-65toer .framer-8lynpm { flex: none; width: 100%; }",
	".framer-G6Ndb.framer-v-192p4h3.framer-1mpnhrg, .framer-G6Ndb.framer-v-14cm3v9.framer-1mpnhrg, .framer-G6Ndb.framer-v-12pc4n3.framer-1mpnhrg, .framer-G6Ndb.framer-v-1jpj1gq.framer-1mpnhrg { width: 390px; }",
	".framer-G6Ndb.framer-v-192p4h3 .framer-1crz8ec, .framer-G6Ndb.framer-v-14cm3v9 .framer-1crz8ec, .framer-G6Ndb.framer-v-12pc4n3 .framer-1crz8ec, .framer-G6Ndb.framer-v-1jpj1gq .framer-1crz8ec { flex-direction: column; gap: 20px; }",
	".framer-G6Ndb.framer-v-192p4h3 .framer-1wdo29, .framer-G6Ndb.framer-v-192p4h3 .framer-8lynpm, .framer-G6Ndb.framer-v-14cm3v9 .framer-1wdo29, .framer-G6Ndb.framer-v-14cm3v9 .framer-8lynpm, .framer-G6Ndb.framer-v-12pc4n3 .framer-1wdo29, .framer-G6Ndb.framer-v-12pc4n3 .framer-8lynpm, .framer-G6Ndb.framer-v-1jpj1gq .framer-1wdo29, .framer-G6Ndb.framer-v-1jpj1gq .framer-8lynpm { flex: none; gap: 20px; width: 100%; }",
	...css,
	'.framer-G6Ndb[data-border="true"]::after, .framer-G6Ndb [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerQn4oD_GJt = withCSS2(Component2, css4, "framer-G6Ndb");
var stdin_default2 = FramerQn4oD_GJt;
FramerQn4oD_GJt.displayName = "Whom Card";
FramerQn4oD_GJt.defaultProps = {
	height: 364,
	width: 1120,
};
addPropertyControls2(FramerQn4oD_GJt, {
	variant: {
		options: [
			"Bhf7mgZFO",
			"DUNJaa_2U",
			"Vzk9SujVN",
			"Bh0KC_eZ8",
			"xYtUMozi0",
			"Oq2rHCdCh",
			"Ts3BiCBo9",
			"kuzZryZVE",
			"j8w88SHnc",
			"d9Fsj5WpK",
			"jVCEOzxXJ",
			"AUoTRH9MD",
		],
		optionTitles: [
			"Desktop 1",
			"Desktop 2",
			"Desktop 3",
			"Desktop 4",
			"Tablet 1",
			"Tablet 2",
			"Tablet 3",
			"Tablet 4",
			"Phone 1",
			"Phone 2",
			"Phone 3",
			"Phone 4",
		],
		title: "Variant",
		type: ControlType2.Enum,
	},
	EfD_tVDRE: {
		defaultValue:
			"Unlock AI\u2019s potential to optimize operations, enhance customer experiences, drive data-informed decisions, and stay competitive in a fast-evolving market.",
		displayTextArea: false,
		title: "Business man",
		type: ControlType2.String,
	},
	DICEOonaS: {
		defaultValue:
			"Identify breakthrough innovations, connect with disruptive startups, gain deep insights into AI trends, and uncover your next big opportunity.",
		displayTextArea: false,
		title: "Investors",
		type: ControlType2.String,
	},
	HrCFO37Cw: {
		defaultValue:
			"Learn how to build smarter products, scale faster with AI-driven tools, refine your strategy with expert guidance, and meet future collaborators or backers.",
		displayTextArea: false,
		title: "Founders",
		type: ControlType2.String,
	},
	AOzSz5R2Y: {
		defaultValue:
			"Explore powerful new frameworks, join immersive technical sessions, solve real-world problems with AI, and grow within a thriving dev community.",
		displayTextArea: false,
		title: "Developers",
		type: ControlType2.String,
	},
});
addFonts2(
	FramerQn4oD_GJt,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PolygonsFonts,
		...getFontsFromSharedStyle2(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:whom-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "j8w88SHnc",
	md: "xYtUMozi0",
	xl: "Bhf7mgZFO",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0ab435b455d76c767a5dea9600bc5786a15f10b45126633827329afa7ac48a86"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders WhomCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0ab435b455d76c767a5dea9600bc5786a15f10b45126633827329afa7ac48a86"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var whom_card_default = ComponentWithRoot;
export { whom_card_default as default };
